<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */

/**
 * Default view for the integration module.
 * 
 * @package views
 */
?>

<h1>
   <?php echo $this->translate('Data integration module');?>
</h1>

<div class="left-column">
	<div class="moduletable_menu">

		<ul id="appmenu" class="menu">

<?php
$user_session = new Zend_Session_Namespace('user');
$role = $user_session->role;
?>


<li><a
				href="<?php echo $this->url(array('controller'=>'integration','action'=>'show-data-submission-page'), null, true) ?>"><?php echo $this->translate('Submit Data');?></a>
			</li>

		</ul>
	</div>
</div>