<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */


/**
 * View for showing errors.
 * @package views
 */
?>


<h1>
  <?php echo $this->translate('Data integration module');?> - <?php echo $this->translate('Error');?>
</h1>
<div class="error-msg">
    <img class="status-img" src="<?php echo  $this->baseUrl('img/Red_x.png') ?>" /><?php echo $this->errorMessage ?>
</div>
<div class="bottom-menu">
    <a href="<?php echo $this->baseUrl('integration/show-data-submission-page') ?>"><b><?php echo $this->translate('Submit Data');?></b></a>
</div>