<H1><?= $this->translate('Indices');?></H1>

<table class="sectiontable">
<tr>
	<th></th>
	<th><?=$this->translate('Index');?></th>
	<th><?=$this->translate('Details');?></th>
	<th></th>
	<th></th>
</tr>
<?php
$i = 0;
foreach ($this->indices as $indexKey => $index) {
?>
<tr class="sectiontableentry<?=$i % 2?>">
	<td class="files-list-cell"><a title="<?=$this->translate('View the files list');?>" href="<?= $this->url(array('controller'=>'pdfmetadata','action'=>'list', 'INDEX_KEY'=>$indexKey), 'default', true)?>"></a></td>
	<td>
	    <p><b><?=$this->translate($indexKey.'Label')?></b></p>
	    <p><?=$this->translate($indexKey.'Definition')?></p>
	</td>
	<td>
	    <p><?=$this->translate('Index size: ') . $index['indexSize']; ?></p>
        <p><?=$this->translate('Number of documents: ') . $index['documentsCount']; ?></p>
        <p><b><?=$this->translate('Index directory: ') . '</b><p>'.$index['indexDirectory'].'</p>'?></p>
        <p><b><?php 
            echo $this->translate('Files directories: ').'</b>';
	        foreach ($index['filesDirectories'] as $filesDirectory) {
	            echo "<p>$filesDirectory</p>";
	        }
        ?></p>
    </td>
	<td class="index-cell"><a title="<?=$this->translate('Index the files presents into the files directories');?>" href="<?= $this->url(array('controller'=>'fileindexation','action'=>'indexpdfs', 'INDEX_KEY'=>$indexKey), 'default', true)?>"></a></td>
	<td class="optimize-cell"><a title="<?=$this->translate('Optimize the index');?>" href="<?= $this->url(array('controller'=>'fileindexation','action'=>'optimize', 'INDEX_KEY'=>$indexKey), 'default', true)?>"></a></td>
</tr>
<?php
$i++;
}
?>
</table>
 
<p class="subTableLink">
    <a href="<?= $this->url(array('controller'=>'index'), null, true) ?>"><?= $this->translate('Back');?></a>
</p>