<?php
/**
 * View for the file indexation index.
 * @package views
 */
?>
<script type="text/javascript" src="<?= $this->baseUrl('js/progressbar.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/extjs/adapter/ext/ext-base.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/extjs/ext-all-debug.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/genapp.js') ?>"></script>

<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('js/extjs/resources/css/ext-all.css') ?>" />
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('js/genapp/resources/css/genapp.pack-min.css') ?>" />

<script type="text/javascript">
	Genapp.util.indexationPage = {
	    progressBar:[]
	};

	Genapp.util.indexationPage.launchIndexPdf = function(indexKey, update){

	    Genapp.util.indexationPage.setupProgressBar(indexKey);

        Ext.Ajax.request({
			url: '<?= $this->baseUrl('/fileindexation/launchindex')?>',
			params:{
				'INDEX_KEY': indexKey,
				'UPDATE': update
			},
			callback: function(options, success, response){
			    if(success == true){
			        var d = Ext.decode(response.responseText);
					if(d.success == true){
			        	Genapp.util.indexationPage.getIndexPdfStatus.defer(3000, Genapp.util.indexationPage, [indexKey]);
			        } else {
			    	    Genapp.util.indexationPage.displayError(indexKey, d.errorMessage);
			    	}
			    } else {
			        Genapp.util.indexationPage.displayError(indexKey, 'An error occured.');
				}
			}
		});
	};

	Genapp.util.indexationPage.getIndexPdfStatus = function(indexKey, callback){

	    if(!Genapp.util.indexationPage.progressBar[indexKey]){
	    	Genapp.util.indexationPage.setupProgressBar(indexKey);
	    }

        Ext.Ajax.request({
			url: '<?= $this->baseUrl('/fileindexation/getindexstatus')?>',
			params:{
				INDEX_KEY: indexKey
			},
			callback: callback ? callback : function(options, success, response){
				if(success == true){
					var d = Ext.decode(response.responseText);
					if(d.success == true){
						if ( 0 <= d.progress && d.progress < d.count) {
						    Genapp.util.indexationPage.progressBar[indexKey].updateProgress(d.progress/d.count, 'Loading item ' + d.progress + ' of ' + d.count + '...');
						    Genapp.util.indexationPage.getIndexPdfStatus.defer(3000, Genapp.util.indexationPage, [indexKey]);
						} else if (d.progress == d.count){
				    	    window.location = '<?= $this->baseUrl('/fileindexation'); ?>';
						} else {
						    Genapp.util.indexationPage.displayError(indexKey, 'An error occured.');
						}
					} else {
			    	    Genapp.util.indexationPage.displayError(indexKey, d.errorMessage);
			    	}
				} else {
				    Genapp.util.indexationPage.displayError(indexKey, 'An error occured.');
				}
			}
		});
	};

	Genapp.util.indexationPage.setupProgressBar = function(indexKey){
	    Ext.get('index-cell-bp-create_'+indexKey).setDisplayed(false);
	    Ext.get('index-cell-bp-update_'+indexKey).setDisplayed(false);
	    // Create the progress bar
		// Note : The progressBar container must have the good size before to render the bar
		Ext.get('index-cell_'+indexKey).setWidth(200);
		if(!Genapp.util.indexationPage.progressBar[indexKey]){
		    Genapp.util.indexationPage.progressBar[indexKey] = new Ext.ProgressBar();
	        Genapp.util.indexationPage.progressBar[indexKey].render('index-cell-pb_'+indexKey);
		}
	    Ext.fly('index-cell-pbtext_'+indexKey).update('').setDisplayed(false);
        Genapp.util.indexationPage.progressBar[indexKey].updateProgress(0, 'Initializing...');
        Genapp.util.indexationPage.progressBar[indexKey].show();
	}

	Genapp.util.indexationPage.displayError = function(indexKey, errorMessage){
	    Genapp.util.indexationPage.progressBar[indexKey].reset(true);
	    Ext.fly('index-cell-pbtext_'+indexKey).update(errorMessage).setDisplayed(true);
		Ext.get('index-cell-bp-create_'+indexKey).setDisplayed(true);
		Ext.get('index-cell-bp-update_'+indexKey).setDisplayed(true);
	    Ext.get('index-cell_'+indexKey).setWidth("auto");
	}

	Ext.onReady(function (){
	<?php
	    foreach ($this->indices as $indexKey => $index) {
			if($index['isRunning']){
		       echo "Genapp.util.indexationPage.getIndexPdfStatus('".$indexKey."');";
			}
        }
    ?>
	},this);


</script>

<H1><?= $this->translate('Indices');?></H1>

<table class="sectiontable">
<tr>
	<th></th>
	<th><?=$this->translate('Index');?></th>
	<th><?=$this->translate('Details');?></th>
	<th></th>
	<th></th>
</tr>
<?php
$i = 0;
foreach ($this->indices as $indexKey => $index) {
?>
<tr class="sectiontableentry<?=$i % 2?>">
	<td class="files-list-cell"><a title="<?=$this->translate('View the files list');?>" href="<?= $this->url(array('controller'=>'pdfmetadata','action'=>'list', 'INDEX_KEY'=>$indexKey), 'default', true)?>"></a></td>
	<td class="index-label-cell">
	    <p><b><?=$this->translate($indexKey.'Label')?></b></p>
	    <p><?=$this->translate($indexKey.'Definition')?></p>
	</td>
	<td>
	    <p><?=$this->translate('Index size:') .'&nbsp;'. $index['indexSize']; ?></p>
        <p><?=$this->translate('Number of documents:') .'&nbsp;'. $index['documentsCount']; ?></p>
        <p><b><?=$this->translate('Index directory:') .'&nbsp;'. '</b><p>'.$index['indexDirectory'].'</p>'?></p>
        <p><b><?php 
            echo $this->translate('Files directories:').'&nbsp;'.'</b>';
	        foreach ($index['filesDirectories'] as $filesDirectory) {
	            echo "<p>$filesDirectory</p>";
	        }
        ?></p>
    </td>
	<td id="index-cell_<?=$indexKey?>" class="index-cell">
        <div id="index-cell-pbtext_<?=$indexKey?>"></div>
        <div id="index-cell-pb_<?=$indexKey?>"></div>
        <a id="index-cell-bp-create_<?=$indexKey?>" title="<?=$this->translate('Create a new index and index the files presents into the files directories');?>" href="javascript:Genapp.util.indexationPage.launchIndexPdf('<?= $indexKey ?>',false);"></a>
        <a id="index-cell-bp-update_<?=$indexKey?>" title="<?=$this->translate('Add/Remove the new/deleted files of the files directories into the existing index');?>" href="javascript:Genapp.util.indexationPage.launchIndexPdf('<?= $indexKey ?>',true);"></a>
    </td>
	<td class="optimize-cell"><a title="<?=$this->translate('Optimize the index');?>" href="<?= $this->url(array('controller'=>'fileindexation','action'=>'optimize', 'INDEX_KEY'=>$indexKey), 'default', true)?>"></a></td>
</tr>
<?php
$i++;
}
?>
</table>

<p class="subTableLink">
    <a href="<?= $this->url(array('controller'=>'index'), null, true) ?>"><?= $this->translate('Back');?></a>
</p>