<H1><?= $this->translate('File Content');?></H1>

<div class="password-change-user-name">
    <?=$this->translate('Content of the file:');?>&nbsp;<b><?=$this->file?></b>
</div>

<p class="file_contents"><?= $this->content;?></p>

<p class="subTableLink">
    <a href="<?= $this->url(array('controller'=>'pdfmetadata', 'action'=>'list', 'INDEX_KEY'=>$this->indexKey), 'default', true) ?>"><?= $this->translate('Back');?></a>
</p>