<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */


/**
 * Show the users of the web site.
 * @package views
 */
?>
<h1>
   <?php echo $this->translate('Users');?>
</h1>


<table class="sectiontable">
<tr>
	<th></th>
	<th></th>
	<th><?php echo $this->translate('User Login');?></th>
	<th><?php echo $this->translate('User Name');?></th>
	<th><?php echo $this->translate('Provider');?></th>
	<th><?php echo $this->translate('Email');?></th>
	<th><?php echo $this->translate('Roles');?></th>
	<th></th>
</tr>
<?php
$i = 0;
foreach($this->users as $user) {
?>
<tr class="sectiontableentry<?php echo $i % 2?>">
	<td class="edit-cell"><a title="<?php echo $this->translate('Edit');?>" href="<?php echo  $this->url(array('controller'=>'usermanagement','action'=>'show-edit-user'), null, true)?>?userLogin=<?php echo $user->login;?>">&nbsp;</a></td>
	<td class="change-password-cell"><a title="<?php echo $this->translate('Change Password');?>" href="<?php echo  $this->url(array('controller'=>'usermanagement','action'=>'show-change-password'), null, true)?>?userLogin=<?php echo $user->login;?>">&nbsp;</a></td>
	<td><?php echo  $this->escape($user->login); ?></td>
	<td><?php echo  $this->escape($user->username); ?></td>
	<td><?php echo  $this->escape($user->provider->label); ?></td>
	<td><?php echo  $this->escape($user->email); ?></td>
	<td><?php foreach ($user->rolesList as $role) {
		echo $role->label."<br/>";
	} ?>
	</td>
	<td class="delete-cell"><a title="<?php echo $this->translate('Delete');?>" href="<?php echo  $this->url(array('controller'=>'usermanagement','action'=>'delete-user'), null, true)?>?userLogin=<?php echo $user->login;?>" onClick="return confirm('<?php echo $this->translate('Are you sure?')?>');">&nbsp;</a></td>
</tr>
<?php
$i++;
}
?>
</table>

<p class="subTableLink">
    <a href="<?php echo  $this->url(array('controller'=>'usermanagement','action'=>'show-create-user'), null, true) ?>"><?php echo $this->translate('Create User');?></a>
<p/>