<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */


/**
 * Show the roles of the web site.
 * @package views
 */
?>
<h1>
   <?php echo $this->translate('Roles');?>
</h1>


<table class="sectiontable">
<tr>
	<th></th>
	<th><?php echo $this->translate('Code');?></th>
	<th><?php echo $this->translate('Label');?></th>
	<th><?php echo $this->translate('Definition');?></th>
	<th></th>
</tr>
<?php
$i = 0;
foreach ($this->roles as $role) {
?>
<tr class="sectiontableentry<?php echo $i % 2?>">
	<td class="edit-cell"><a title="<?php echo $this->translate('Edit');?>" href="<?php echo  $this->url(array('controller'=>'usermanagement','action'=>'show-edit-role'), null, true)?>?roleCode=<?php echo $role->code;?>">&nbsp;</a></td>
	<td><?php echo  $this->escape($role->code); ?></td>
	<td><?php echo  $this->escape($role->label); ?></td>
	<td><?php echo  $this->escape($role->definition); ?></td>
	<td class="delete-cell"><a title="<?php echo $this->translate('Delete');?>" href="<?php echo  $this->url(array('controller'=>'usermanagement','action'=>'delete-role'), null, true)?>?roleCode=<?php echo $role->code;?>" onClick="return confirm('<?php echo $this->translate('Are you sure?')?>');">&nbsp;</a></td>
</tr>
<?php
	$i++;
}
?>
</table>
 
<p class="subTableLink">
    <a href="<?php echo  $this->url(array('controller'=>'usermanagement','action'=>'show-create-role'), null, true) ?>"><?php echo $this->translate('Create Role');?></a>
<p/>
