<?php

namespace OGAMBundle\Repository\HarmonizedData;

/**
 * HarmonizationProcessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HarmonizationProcessRepository extends \Doctrine\ORM\EntityRepository
{
}
