<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 * 
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices. 
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents. 
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */
 
/**
 * View for the file indexation index.
 * @package views
 */
?>

<H1><?= $this->translate('Indexed files list');?></H1>

<table class="sectiontable">
<tr>
	<th></th>
	<th></th>
	<th></th>
	<th><?=$this->translate('Files');?></th>
	<th></th>
	<th></th>
</tr>

<?php
$i = 0;
foreach ($this->files as $file) {
?>
<tr class="sectiontableentry<?=$i % 2?>">
    <td class="pdf-cell"><a href="<?= $this->url(array('controller'=>'indexedpdffile',
                                 'action'=>'viewpdf',
                                 'file' =>urlencode($file) ),'default', true)?>" title="<?=$this->translate('View the file')?>">&nbsp;</a></td>
    <td class="view-content-cell"><a href="<?= $this->url(array('controller'=>'indexation',
                                 'action'=>'parsepdf',
                                 'INDEX_KEY'=>$this->indexKey,
                                 'file' =>urlencode($file) ),'default', true)?>" title="<?=$this->translate('View the file content')?>">&nbsp;</a></td>
	<td class="view-meta-cell"><a href="<?= $this->url(array('controller'=>'indexedpdffile',
                                 'action'=>'viewmeta',
                                 'INDEX_KEY'=>$this->indexKey,
                                 'file' =>urlencode($file) ),'default', true)?>" title="<?=$this->translate('View the file metadata')?>">&nbsp;</a></td>
	<td><?=$file?></td>
	<td class="edit-cell"><a href="<?= ""/*$this->url(array('controller'=>'indexedpdffile',
                                 'action'=>'editmeta',
                                 'file' =>urlencode($file) ),'default', true) */?>" title="<?=$this->translate('Edit the Metadata')?>" onClick="alert('<?=$this->translate("Not implemented");?>')">&nbsp;</a></td>
    <td class="delete-cell"><a href="<?= ""/*$this->url(array('controller'=>'indexation',
                                 'action'=>'removefile' ),'default', true) */?>" title="<?=$this->translate('Remove the file of the index')?>" onClick="return alert('<?=$this->translate('Not implemented');?>');">&nbsp;</a></td>
</tr>
<?php
$i++;
}
?>
</table>
 
<p class="subTableLink">
    <a href="<?= $this->url(array('controller'=>'indexation'), null, true) ?>"><?= $this->translate('Back');?></a>
</p>