<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 * 
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices. 
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents. 
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */
 
/**
 * View for the file indexation index.
 * @package views
 */
?>

<H1><?= $this->translate('File metadata');?></H1>

<div class="password-change-user-name">
    <?=$this->translate('Meta data of the file:');?>&nbsp;<b><?=$this->file?></b>
</div>

<table class="sectiontable">
<tr>
	<th><?=$this->translate('Meta Name');?></th>
	<th><?=$this->translate('Meta Value');?></th>
</tr>

<?php
$i = 0;
  foreach ($this->metaValues as $metaName => $metaValue) {
?>
<tr class="sectiontableentry<?=$i % 2?>">
	<td><?=$metaName?></td>
	<td><?=$metaValue?></td>
</tr>
<?php
$i++;
}
?>
</table>
 
<p class="subTableLink">
    <a href="<?= ""/*$this->url(array('controller'=>'indexedpdffile', 'action'=>'editmeta', 'file' =>urlencode($this->file) ),'default', true) */?>" title="<?=$this->translate('Edit the Metadata')?>" onClick="alert('<?=$this->translate("Not implemented");?>')"><?= $this->translate("Edit the Metadata")?></a>
    &nbsp;/&nbsp;&nbsp;<a href="<?= $this->url(array('controller'=>'indexation', 'action'=>'parsepdf', 'file' =>urlencode($this->file), 'INDEX_KEY'=>$this->indexKey), 'default', true) ?>"><?= $this->translate('View the file content');?></a>
    &nbsp;/&nbsp;&nbsp;<a href="<?= $this->url(array('controller'=>'indexedpdffile', 'action'=>'list', 'INDEX_KEY'=>$this->indexKey), 'default', true) ?>"><?= $this->translate('Back');?></a>
</p>