<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */



/**
 * Parameters for the map.
 * @package views
 */
?>
	// This file containts Javascript
	
	
	//
	// Define the map parameters
	// 
	OgamDesktop = {};
	
	OgamDesktop.map = {};
	
	OgamDesktop.map.defaultzoom = <?= $this->defaultzoom ?>;
	OgamDesktop.map.x_center = <?= $this->x_center ?>;
	OgamDesktop.map.y_center = <?= $this->y_center ?>;
	OgamDesktop.map.resolutions = [<?= $this->resolutions ?>];
	OgamDesktop.map.numZoomLevels = [<?= $this->numZoomLevels ?>];
	OgamDesktop.map.projection = '<?= $this->projection ?>';
	OgamDesktop.map.tilesize= <?= $this->tilesize ?>;

	OgamDesktop.map.x_min= <?= $this->bbox_x_min ?>;
	OgamDesktop.map.y_min= <?= $this->bbox_y_min ?>;
	OgamDesktop.map.x_max= <?= $this->bbox_x_max ?>;
	OgamDesktop.map.y_max= <?= $this->bbox_y_max ?>;
	
	OgamDesktop.map.featureinfo_margin = <?= $this->featureinfo_margin ?>;
	OgamDesktop.map.featureinfo_typename = '<?= $this->featureinfo_typename ?>';
	OgamDesktop.map.featureinfo_maxfeatures = <?= $this->featureinfo_maxfeatures ?>;