<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */


/**
 * View for showing errors.
 * @package views
 */
?>


<h1>
   <?php echo $this->translate('Data harmonization module');?>
</h1>

<br/>
<br/>
<?php echo $this->errorMessage ?>&nbsp;<img src="<?php echo $this->baseUrl('img/Red_x.png') ?>" height='32' />
<br/>
<br/>
<a href="<?= $this->baseUrl('harmonization') ?>"><b>Back</b></a>