# Environment-specific settings used by the provisioning process

#
# !!! DO NOT EDIT THIS FILE !!!
#
# Copy the file in the same directory and rename into "local_config.sh".
# Edit the "local_config.sh" file.


ENVIRONMENT='Local VM'


DATABASE=ogam
USERNAME=postgres


# Geoportail API Key, replace by your key (see http://professionnels.ign.fr/)
GEOPORTAIL_API_KEY='7gr31kqe5xttprd2g7zbkqgo'
