# Environment-specific settings used by the provisioning process

#
# !!! DO NOT EDIT THIS FILE !!!
#
# Copy the file in the same directory and rename into "local_config.sh".
# Edit the "local_config.sh".


# Required
environment='Local VM'
baseUrl='http://192.168.50.4/'
domain='ogam.fr'


# Optional
GEOPORTAIL_API_KEY='7gr31kqe5xttprd2g7zbkqgo'
