<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */



/**
 * Default view for the data querying module.
 * @package views
 */
?>
	
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('js/ext/packages/ext-theme-gray/build/resources/ext-theme-gray-all-debug.css') ?>" /> 
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('js/build/production/Ogam/resources/Ogam-all.css') ?>" />
<script type="text/javascript" src="<?= $this->baseUrl('js/ext/ext-all-debug.js') ?>"></script>  
<script type="text/javascript" src="<?= $this->baseUrl('js/ext/packages/ext-theme-gray/build/ext-theme-gray-debug.js') ?>"></script> 

<!-- <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('js/ext/packages/ext-theme-gray/build/resources/ext-theme-gray-all-debug-v5.0.0.css') ?>" />--> 
<!-- <script type="text/javascript" src="http://cdn.sencha.com/ext/gpl/5.0.0/build/ext-all-debug.js"</script>--> 


<!-- The line below must be kept intact for Sencha Cmd to build your application -->
<!-- <script id="microloader" type="text/javascript" src="<?= $this->baseUrl('js/bootstrap.js') ?>"></script> -->
<script id="microloader" type="text/javascript" src="<?= $this->baseUrl('js/build/production/Ogam/app.js') ?>"></script>
    
<div id='page'></div>

<!-- Fields required for history management -->
<form id="history-form" class="x-hidden">
	<input type="hidden" id="x-history-field" />
	<iframe id="x-history-frame"></iframe>
</form>

