<?php

namespace Ign\Bundle\OGAMBundle\Repository\Metadata;

/**
 * ChecksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChecksRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $submissionId
     * @return Array
     */
    public function getSubmissionCheckCount($submissionId): array
    {
      $conn = $this->getEntityManager()->getConnection();

      $sql = '
          SELECT c.*, count(*) as count
          FROM raw_data.check_error ce
          INNER JOIN metadata.checks c USING(check_id)
          WHERE ce.submission_id = :submission_id
          GROUP BY c.check_id
          ORDER BY count ASC
          ';
      $stmt = $conn->prepare($sql);
      $stmt->execute(['submission_id' => $submissionId]);

      // returns an array of arrays (i.e. a raw data set)
      return $stmt->fetchAll();
    }
}
