<?php

namespace OGAMBundle\Repository\Metadata;

/**
 * DatasetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatasetRepository extends \Doctrine\ORM\EntityRepository
{
}
