<?php

namespace OGAMBundle\Repository\Metadata;

/**
 * FieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldRepository extends \Doctrine\ORM\EntityRepository
{
}
