<?php

namespace OGAMBundle\Repository\Metadata;

/**
 * FileFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileFieldRepository extends \Doctrine\ORM\EntityRepository
{
}
