<?php

namespace OGAMBundle\Repository\Metadata;

/**
 * FileFormatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileFormatRepository extends \Doctrine\ORM\EntityRepository
{
}
