<?php

namespace OGAMBundle\Repository\Metadata;

/**
 * FormFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormFieldRepository extends \Doctrine\ORM\EntityRepository
{
}
