<?php

namespace OGAMBundle\Repository\Metadata;

/**
 * FormatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormatRepository extends \Doctrine\ORM\EntityRepository
{
}
