<?php

namespace OGAMBundle\Repository\Metadata;

/**
 * FormFormatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormFormatRepository extends \Doctrine\ORM\EntityRepository
{
}
