<?php

namespace OGAMBundle\Repository\Metadata;

/**
 * ModeTreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeTreeRepository extends \Doctrine\ORM\EntityRepository
{
}
