<?php

namespace OGAMBundle\Repository\Metadata;

/**
 * ModeTaxrefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeTaxrefRepository extends \Doctrine\ORM\EntityRepository
{
}
