<?php

namespace OGAMBundle\Repository\Metadata;

/**
 * RangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RangeRepository extends \Doctrine\ORM\EntityRepository
{
}
