<?php

namespace OGAMBundle\Repository\Metadata;

/**
 * SchemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchemaRepository extends \Doctrine\ORM\EntityRepository
{
}
