<?php

namespace OGAMBundle\Repository\Metadata;

/**
 * TableFormatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableFormatRepository extends \Doctrine\ORM\EntityRepository
{
}
