<?php

namespace OGAMBundle\Repository\Metadata;

/**
 * tableTreeDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tableTreeDataRepository extends \Doctrine\ORM\EntityRepository
{
}
