<?php

namespace OGAMBundle\Repository\Metadata;

/**
 * TableTreeDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableTreeDataRepository extends \Doctrine\ORM\EntityRepository
{
}
