<?php
namespace OGAMBundle\Repository\Metadata;

use OGAMBundle\Entity\Metadata\Unit;
use OGAMBundle\OGAMBundle;
use OGAMBundle\Entity\Metadata\Mode;
use OGAMBundle\Entity\Metadata\Dynamode;
use OGAMBundle\Entity\Metadata\ModeTree;
use OGAMBundle\Entity\Metadata\ModeTaxref;

/**
 * UnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitRepository extends \Doctrine\ORM\EntityRepository
{

    public function getModes(Unit $unit)
    {
        /*
         * Must handle these cases :
         * CODE MODE
         * CODE DYNAMIC
         * CODE TREE
         * CODE TAXREF
         * ARRAY MODE
         * ARRAY DYNAMIC
         * ARRAY TREE
         * ARRAY TAXREF
         */
        if ($unit->getType() === "CODE" or $unit->getType() === "ARRAY") {
            switch ($unit->getSubtype()) {
                case "MODE":
                    return $this->_em->getRepository(Mode::class)->findBy(array(
                        'unit' => $unit->getUnit()
                    ));
                case "DYNAMIC":
                    return $this->_em->getRepository(Dynamode::class)->getModes($unit);
                case "TREE": // TODO: Manage the TREE case
                case "TAXREF": // TODO: Manage the TAXREF case
                default:
                    return null;
            }
        }
    }
}