<H1><?= $this->translate('Check result');?></H1>
<H2><?= $this->translate('PHP Parameters');?></H2>
<UL>
<?php
foreach ($this->phpParameters as $param) {
    echo '<LI><B>'.$param['name'].'&nbsp;:</B>&nbsp;'.$this->translate('Expected value').'&nbsp;'.$param['value'];
    if(empty($param['error'])){
        echo '<SPAN style="color:green;">&nbsp;-&nbsp;ok</SPAN><BR/></LI>';
    } else {
        echo '<SPAN style="color:red;">&nbsp;-&nbsp;'.$param['error'].'</SPAN><BR/></LI>';
    }
}
?>
</UL>


<H2><?= $this->translate('Database');?></H2>

Note : The database user must have administration rights to perform these tests

<H4>Checking for missing tables</H4>
<?php 
if (count($this->missingTablesMsg)==0) {
	echo '<SPAN style="color:green;">ok</SPAN>';
} else {
	echo '<UL>';
	foreach ($this->missingTablesMsg as $msg) {
		echo '<LI><B>'.$msg.'</B></LI>';
	}
	echo '</UL>';
}
?>

<H4>Checking for primary keys</H4>
<?php 
if (count($this->primaryKeysMsg)==0) {
	echo '<SPAN style="color:green;">ok</SPAN>';
} else {
	echo '<UL>';
	foreach ($this->primaryKeysMsg as $msg) {
		echo '<LI><B>'.$msg.'</B></LI>';
	}
	echo '</UL>';
}
?>


<H4>Checking for missing fields</H4>
<?php 
if (count($this->missingFieldsMsg)==0) {
	echo '<SPAN style="color:green;">ok</SPAN>';
} else {
	echo '<UL>';
	foreach ($this->missingFieldsMsg as $msg) {
		echo '<LI><B>'.$msg.'</B></LI>';
	}
	echo '</UL>';
}
?>


<H4>Checking field types</H4>
<?php 
if (count($this->fieldTypeMsg)==0) {
	echo '<SPAN style="color:green;">ok</SPAN>';
} else {
	echo '<UL>';
	foreach ($this->fieldTypeMsg as $msg) {
		echo '<LI><B>'.$msg.'</B></LI>';
	}
	echo '</UL>';
}
?>
