<H1><?= $this->translate('Check result');?></H1>
<DIV CLASS="checkconf-page">
<H2><?= $this->translate('PHP Parameters');?></H2>
<UL>
<?php
foreach ($this->phpParameters as $param) {
    echo '<LI><B>'.$param['name'].'&nbsp;:</B>&nbsp;'.$this->translate('Expected value').'&nbsp;'.$param['value'];
    if(empty($param['error'])){
        echo '<SPAN class="green">&nbsp;-&nbsp;ok</SPAN><BR/></LI>';
    } else {
        echo '<SPAN class="red">&nbsp;-&nbsp;'.$param['error'].'</SPAN><BR/></LI>';
    }
}
?>
</UL>


<H2><?= $this->translate('Database');?></H2>
<span class="note">
    <?= $this->translate('Note: The database user must have administration rights to perform these tests.');?>
</span>


<H4><?= $this->translate('Checking for missing schemas:');?></H4>
<?php 
if (count($this->missingSchemasMsg)==0) {
	echo '<UL><LI><SPAN class="green">ok</SPAN></LI></UL>';
} else {
	echo '<UL>';
	foreach ($this->missingSchemasMsg as $msg) {
		echo '<LI><SPAN class="red">'.$msg.'</SPAN></LI>';
	}
	echo '</UL>';
}
?>


<H4><?= $this->translate('Checking for missing tables:');?></H4>
<?php 
if (count($this->missingTablesMsg)==0) {
	echo '<UL><LI><SPAN class="green">ok</SPAN></LI></UL>';
} else {
	echo '<UL>';
	foreach ($this->missingTablesMsg as $msg) {
		echo '<LI><SPAN class="red">'.$msg.'</SPAN></LI>';
	}
	echo '</UL>';
}
?>

<H4><?= $this->translate('Checking for primary keys:');?></H4>
<?php 
if (count($this->primaryKeysMsg)==0) {
	echo '<UL><LI><SPAN class="green">ok</SPAN></LI></UL>';
} else {
	echo '<UL>';
	foreach ($this->primaryKeysMsg as $msg) {
		echo '<LI><SPAN class="red">'.$msg.'</SPAN></LI>';
	}
	echo '</UL>';
}
?>


<H4><?= $this->translate('Checking for missing fields:');?></H4>
<?php 
if (count($this->missingFieldsMsg)==0) {
	echo '<UL><LI><SPAN class="green">ok</SPAN></LI></UL>';
} else {
	echo '<UL>';
	foreach ($this->missingFieldsMsg as $msg) {
		echo '<LI><SPAN class="red">'.$msg.'</SPAN></LI>';
	}
	echo '</UL>';
}
?>


<H4><?= $this->translate('Checking field types:');?></H4>
<?php 
if (count($this->fieldTypeMsg)==0) {
	echo '<UL><LI><SPAN class="green">ok</SPAN></LI></UL>';
} else {
	echo '<UL>';
	foreach ($this->fieldTypeMsg as $msg) {
		echo '<LI><SPAN class="red">'.$msg.'</SPAN></LI>';
	}
	echo '</UL>';
}
?>

<H4><?= $this->translate('Checking foreign keys:');?></H4>
<?php 
if (count($this->missingFKsMsg)==0) {
	echo '<UL><LI><SPAN class="green">ok</SPAN></LI></UL>';
} else {
	echo '<UL>';
	foreach ($this->missingFKsMsg as $msg) {
		echo '<LI><SPAN class="red">'.$msg.'</SPAN></LI>';
	}
	echo '</UL>';
}
?>
</DIV>