<?php 
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 * 
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices. 
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents. 
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */

/**
 * View for the check of the configuration of the system.
 * @package views
 */
?>

<H1><?php echo $this->translate('Check result');?></H1>
<DIV CLASS="checkconf-page">
<H2><?php echo $this->translate('PHP Parameters');?></H2>
<UL>
<?php
foreach ($this->phpParameters as $param) {
    echo '<LI><B>'.$param['name'].'&nbsp;:</B>&nbsp;'.$this->translate('Expected value').'&nbsp;'.$param['value'];
    if(empty($param['error'])){
        echo '<SPAN class="green">&nbsp;-&nbsp;ok</SPAN><BR/></LI>';
    } else {
        echo '<SPAN class="red">&nbsp;-&nbsp;'.$param['error'].'</SPAN><BR/></LI>';
    }
}
?>
</UL>


<H2><?php echo $this->translate('Database');?></H2>
<span class="note">
    <?php echo $this->translate('Note: The database user must have administration rights to perform these tests.');?>
</span>


<H4><?php echo $this->translate('Checking for missing schemas:');?></H4>
<?php 
if (count($this->missingSchemasMsg)==0) {
	echo '<UL><LI><SPAN class="green">ok</SPAN></LI></UL>';
} else {
	echo '<UL>';
	foreach ($this->missingSchemasMsg as $msg) {
		echo '<LI><SPAN class="red">'.$msg.'</SPAN></LI>';
	}
	echo '</UL>';
}
?>


<H4><?php echo $this->translate('Checking for missing tables:');?></H4>
<?php 
if (count($this->missingTablesMsg)==0) {
	echo '<UL><LI><SPAN class="green">ok</SPAN></LI></UL>';
} else {
	echo '<UL>';
	foreach ($this->missingTablesMsg as $msg) {
		echo '<LI><SPAN class="red">'.$msg.'</SPAN></LI>';
	}
	echo '</UL>';
}
?>

<H4><?php echo $this->translate('Checking for primary keys:');?></H4>
<?php 
if (count($this->primaryKeysMsg)==0) {
	echo '<UL><LI><SPAN class="green">ok</SPAN></LI></UL>';
} else {
	echo '<UL>';
	foreach ($this->primaryKeysMsg as $msg) {
		echo '<LI><SPAN class="red">'.$msg.'</SPAN></LI>';
	}
	echo '</UL>';
}
?>


<H4><?php echo $this->translate('Checking for missing fields:');?></H4>
<?php 
if (count($this->missingFieldsMsg)==0) {
	echo '<UL><LI><SPAN class="green">ok</SPAN></LI></UL>';
} else {
	echo '<UL>';
	foreach ($this->missingFieldsMsg as $msg) {
		echo '<LI><SPAN class="red">'.$msg.'</SPAN></LI>';
	}
	echo '</UL>';
}
?>


<H4><?php echo $this->translate('Checking field types:');?></H4>
<?php 
if (count($this->fieldTypeMsg)==0) {
	echo '<UL><LI><SPAN class="green">ok</SPAN></LI></UL>';
} else {
	echo '<UL>';
	foreach ($this->fieldTypeMsg as $msg) {
		echo '<LI><SPAN class="red">'.$msg.'</SPAN></LI>';
	}
	echo '</UL>';
}
?>

<H4><?php echo $this->translate('Checking foreign keys:');?></H4>
<?php 
if (count($this->missingFKsMsg)==0) {
	echo '<UL><LI><SPAN class="green">ok</SPAN></LI></UL>';
} else {
	echo '<UL>';
	foreach ($this->missingFKsMsg as $msg) {
		echo '<LI><SPAN class="red">'.$msg.'</SPAN></LI>';
	}
	echo '</UL>';
}
?>
</DIV>