<?php

/**
 * Parameters for the result grid.
 * @package views
 */
?>

	// This file containts Javascript


	//
	// Define the grid parameters
	//
	Genapp.grid = {};

	Genapp.grid.pagesize = <?=$this->pagesize?>;

	Genapp.grid.hideExportCSV = <?=$this->hideExportCSV?>;
    Genapp.grid.hideAggregationCsvExportMenuItem = <?=$this->hideAggregationCsvExportMenuItem?>;
    Genapp.grid.hideInterpolationMenuItem = <?=$this->hideInterpolationMenuItem?>;
    Genapp.grid.hideAggregationButton = <?=$this->hideAggregationButton?>;