<?php

/**
 * Parameters for the result grid.
 * @package views
 */
?>

if(Genapp.ConsultationPanel){
    Ext.apply(Genapp.ConsultationPanel.prototype, {
        gridPageSize : <?=$this->pagesize?>,
        hideGridCsvExportMenuItem : <?=$this->hideGridCsvExportMenuItem?>,
        hideAggregationCsvExportMenuItem : <?=$this->hideAggregationCsvExportMenuItem?>,
        hideInterpolationButton : <?=$this->hideInterpolationButton?>,
        hideAggregationButton : <?=$this->hideAggregationButton?>,
        hideGridDataEditButton : <?=$this->hideGridDataEditButton?>
    });
}