<?php

namespace OGAMBundle\Repository\Mapping;

/**
 * BoundingBoxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoundingBoxRepository extends \Doctrine\ORM\EntityRepository
{
}
