<?php

namespace OGAMBundle\Repository\Mapping;

/**
 * LayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LayerRepository extends \Doctrine\ORM\EntityRepository
{
}
