<?php

namespace OGAMBundle\Repository\Mapping;

/**
 * LayerServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LayerServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
