<?php

namespace OGAMBundle\Repository\Mapping;

/**
 * LayerTreeNodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LayerTreeNodeRepository extends \Doctrine\ORM\EntityRepository
{
}
