<?php

namespace OGAMBundle\Repository\Mapping;

/**
 * LegendItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegendItemRepository extends \Doctrine\ORM\EntityRepository
{
}
