<?php

namespace OGAMBundle\Repository\Mapping;

use Doctrine\ORM\Query\ResultSetMapping;

/**
 * ResultLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultLocationRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Clean the previous results
	 * @param String $session_id
	 *        	the session id
	 */
	function cleanPreviousResults($session_id){
		$qm = $this->getEntityManager();
		$sql = "DELETE FROM result_location WHERE session_id = ? OR (_creationdt < CURRENT_TIMESTAMP - INTERVAL '2 days')";
		$query = $qm->createNativeQuery($sql, new ResultSetMapping());
		$query->execute(array(
				$session_id
		));
	}
}
