<?php

namespace OGAMBundle\Repository\Mapping;

use Doctrine\DBAL\Connection;

/**
 * ScaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScaleRepository 
{
	private $db;
	
	function __construct(Connection $con)
	{
		$this->db= $con;
	}
	/**
	 * Get the list of available scales.
	 * @return integer[]
	 */
	function getScales(){
		$req = "SELECT scale FROM scales ORDER BY scale DESC";
		$select = $this->db->prepare($req);
		$select->execute(null);
		
		$result = array();
		foreach ($select->fetchAll() as $row) {
			$result[] = $row['scale'];
		}
		return $result;
	}
}
