<?php
/**
 * Login page.
 * @package views
 */
?>
<script  type="text/javascript" language='Javascript' src="<?= $this->baseUrl('js/auth_cram.js') ?>"></script>
<noscript class="noscript">Javascript must be actived in order to login</noscript>


<h1>
   <?=$this->translate('User Module');?>
</h1>
<div class="login-form">
    <h2><?=$this->translate('Please login:');?></h2>
    <?= $this->form ?>
</div>
