<?php

namespace Ign\Bundle\OGAMBundle\Repository\RawData;

/**
 * CheckErrorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckErrorRepository extends \Doctrine\ORM\EntityRepository
{
  /**
   * @param $submissionId
   * @return CheckError[]
   */
  public function getOrderedCheckErrors($submissionId): array
  {
      $qb = $this->createQueryBuilder('ce')
          ->leftJoin('ce.check', 'c')
          ->andWhere('ce.submissionId = :submission_id')
          ->setParameter('submission_id', $submissionId)
          ->orderBy('c.importance', 'ASC')
          ->orderBy('ce.lineNumber', 'ASC')
          ->setMaxResults(100)
          ->getQuery();

    return $qb->execute();
  }
}