<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */


/**
 * Login page.
 * @package views
 */
?>
<script  type="text/javascript" language='Javascript' src="<?php echo $this->baseUrl('js/auth_cram.js') ?>"></script>
<noscript class="noscript">Javascript must be actived in order to login</noscript>

<h1><?php echo $this->translate('Authentication');?></h1>
<?php echo $this->form ?>
