<?php
/**
 * Default view for the harmonization module.
 * @package views
 */
?>

<h1>
   Data harmonization module
</h1>

<div class="left-column">
<div class="moduletable_menu">

<ul id="appmenu" class="menu">

 
<li>
<a href="<?= $this->url(array('controller'=>'harmonization','action'=>'show-harmonization-page'), null, true) ?>">Harmonize Data</a>
</li>


</ul>
</div>
</div>

