<?php
/**
 * View for the harmonization process.
 * @package views
 */
?>


<h1>
   Data Harmonization module
</h1>

<h2>Validated submissions</h2>

<table class="sectiontable">
<tr>
	<th>Dataset</th>
	<th>Country Code</th>	
</tr>

<?
$i = 0;
foreach($this->validatedsubmissions as $validatedSubmission) {
?>
<tr class="sectiontableentry<?=$i % 2?>">
	<td><?= $validatedSubmission->jrcRequest ?></td>	
	<td><?= $this->countries[$validatedSubmission->countryCode]; ?></td>
</tr>
<?
$i++;
}
?>
</table>

<h2>Select a data set</h2>
<div class="data-harmonization-form">
<?= $this->form ?>
</div>
<?= $this->errorMessage ?>