<?php

namespace OGAMBundle\Repository\Website;

/**
 * ApplicationParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationParameterRepository extends \Doctrine\ORM\EntityRepository
{
}
