<?php

namespace OGAMBundle\Repository\Website;

/**
 * PredefinedRequestGroupAssoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PredefinedRequestGroupAssoRepository extends \Doctrine\ORM\EntityRepository
{
}
