<?php

namespace OGAMBundle\Repository\Website;

/**
 * PredefinedRequestCriterionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PredefinedRequestCriterionRepository extends \Doctrine\ORM\EntityRepository
{
}
