<?php

namespace OGAMBundle\Repository\Webiste;

/**
 * PredefinedRequestColumnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PredefinedRequestColumnRepository extends \Doctrine\ORM\EntityRepository
{
}
