<?php

namespace OGAMBundle\Repository\Website;

/**
 * PredefinedRequestGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PredefinedRequestGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
