<?php

namespace OGAMBundle\Repository\Website;

use OGAMBundle\Entity\Metadata\FormField;

/**
 * PredefinedRequestColumnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PredefinedRequestColumnRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get the columns of a predefined request.
     *
     * @param String $requestName
     *        	the name of the request
     * @return Array[PredefinedField] The list of request columns
     */
    public function getPredefinedRequestColumns($requestName, $locale) {
    
        $qb = $this->_em->createQueryBuilder();
        $qb->select('prc')
        ->from('OGAMBundle:Website\PredefinedRequestColumn', 'prc')
        ->where('prc.requestName = :request_name')
        ->setParameters([
            'request_name' => $requestName
        ]);
    
        $columns = $qb->getQuery()->getResult();
    
        // Get the form fields associated to the criteria
        $formFieldRepository = $this->_em->getRepository(FormField::class);
        foreach($columns as $column){
            $formField = $formFieldRepository->getFormField($column->getFormat(), $column->getData(), $locale);
            $column->setFormField($formField);
        }
    
        return $columns;
    }
}
