<?php

namespace OGAMBundle\Repository\RawData;



use Doctrine\Common\Collections\Criteria;

/**
 * SubmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubmissionRepository extends \Doctrine\ORM\EntityRepository
{
	function getAciveSubmissions(){
		 $dql = "SELECT s "
             . "FROM OGAMBundle\Entity\RawData\Submission s "
             . "WHERE s.step NOT IN ('CANCELLED', 'INIT')";

        $query = $this->getEntityManager()->createQuery($dql);

        return $query->getResult();
	}
	/**
	 * Get submissions for Harmonization.
	 *
	 * @return Array[Submission]
	 */
	public function getSubmissionsForHarmonization($orderBy = array('id'=>'ASC')) {

		return $this->matching(Criteria::create()
				->where(Criteria::expr()
						->notIn('step', array('CANCELLED', 'INIT')))
				->orderBy($orderBy));

	}
}
