<?php

namespace OGAMBundle\Repository\RawData;

/**
 * SubmissionFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubmissionFileRepository extends \Doctrine\ORM\EntityRepository
{
}
