<?php
namespace OGAMBundle\Repository\RawData;

use Doctrine\Common\Collections\Criteria;

/**
 * SubmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubmissionRepository extends \Doctrine\ORM\EntityRepository {

	/**
	 * Get some information about the active submissions.
	 *
	 * @param String $providerId
	 *        	provider to get the submissions from (null for all providers)
	 * @return Array[Submission]
	 */
	function getActiveSubmissions($providerId = null) {
		$dql = "SELECT s "
			. "FROM OGAMBundle\Entity\RawData\Submission s "
			. "WHERE s.step NOT IN ('CANCELLED', 'INIT') ";

		if ($providerId) {
             	$dql .= " AND s.provider = :provider ";
		}

		$dql .= "ORDER BY s.id DESC";

		$query = $this->getEntityManager()->createQuery($dql);

		if ($providerId) {
			$query->setParameter('provider', $providerId);
		}

		return $query->getResult();
	}

	/**
	 * Get submissions for Harmonization.
	 *
	 * @return Array[Submission]
	 */
	public function getSubmissionsForHarmonization($orderBy = array('id'=>'ASC')) {
		return $this->matching(Criteria::create()->where(Criteria::expr()->notIn('step', array(
			'CANCELLED',
			'INIT'
		)))
			->orderBy($orderBy));
	}
}
