# Fichier de conf de la navigation : breadcrumb, menus, aide...
# Définit les labels affichés dans les menus.
# On pourrait ajouter des titres de page.

nav:

  home:
    label: Breadcrumb Home
    controller: index
    action: index
    module: default
    help: /index.html
    helpLabel: Aide

    pages:

      integration:
        label: Breadcrumb Integration
        controller: integration
        action: index
        module: default
        help: /import/index.html
        helpLabel: Aide pour l'import de données
        pages:
          newintegration:
            label: Breadcrumb Integration New
            controller: integration
            action: show-create-data-submission
            module: default
          newintegration2:
            label: Breadcrumb Integration New
            controller: integration
            action: validate-create-data-submission
            module: default

      visualisation:
        label: Breadcrumb Visualization
        controller: query
        action: index
        module: default
        help: /recherche-visu/index.html
        helpLabel: Aide pour la visualisation et la recherche de données

      edition:
        label: Breadcrumb Edition
        controller: dataedition
        action: index
        module: default
        pages:
          editionedit:
            label: Breadcrumb Edit Data
            controller: dataedition
            action: show-edit-data
            module: default
          editionadd:
            label: Breadcrumb Add Data
            controller: dataedition
            action: show-add-data
            module: default

      checkconf:
        label: Breadcrumb Check Configuration
        controller: checkconf
        action: index
        module: default

      user:
        label: Breadcrumb User
        controller: user
        action: index
        module: default
        help: /utilisateurs/index.html
        helpLabel: Aide pour la gestion des utilisateurs

      usermanagement:
        label: Breadcrumb Users Administration
        controller: usermanagement
        action: index
        module: default
        help: /utilisateurs/index.html
        helpLabel: Aide pour la gestion des utilisateurs
        pages:

          users:
            label: Breadcrumb Users
            controller: usermanagement
            action: show-users
            module: default
            pages:

              adduser:
                label: Breadcrumb Add User
                controller: usermanagement
                action: show-create-user
                module: default

              edituser:
                label: Breadcrumb Edit User
                controller: usermanagement
                action: show-edit-user
                module: default

              passworduser:
                label: Breadcrumb Change Password
                controller: usermanagement
                action: show-change-password
                module: default

          users2:
            label: Breadcrumb Users
            controller: usermanagement
            action: validate-user
            module: default
          users3:
            label: Breadcrumb Users
            controller: usermanagement
            action: delete-user
            module: default

          roles:
            label: Breadcrumb Roles
            controller: usermanagement
            action: show-roles
            module: default
            pages:

              editrole:
                label: Breadcrumb Edit Role
                controller: usermanagement
                action: show-edit-role
                module: default

              addrole:
                label: Breadcrumb Add Role
                controller: usermanagement
                action: show-create-role
                module: default

          roles2:
            label: Breadcrumb Roles
            controller: usermanagement
            action: validate-role
            module: default
          roles3:
            label: Breadcrumb Roles
            controller: usermanagement
            action: delete-role
            module: default

          providers:
            label: Breadcrumb Providers
            controller: usermanagement
            action: show-providers
            module: default
            pages:

              providerdetails:
                label: Breadcrumb Providers Details
                controller: usermanagement
                action: show-provider-content
                module: default

              editprovider:
                label: Breadcrumb Edit Provider
                controller: usermanagement
                action: edit-provider
                module: default

              addprovider:
                label: Breadcrumb Add Provider
                controller: usermanagement
                action: add-provider
                module: default

          providers2:
            label: Breadcrumb Providers
            controller: usermanagement
            action: delete-provider
            module: default