# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    service_integration_url: "http://localhost:8080/OGAMIntegrationService/"
services:
    ogam.integration_service:
        class: OGAMBundle\Services\Integration
        arguments: ["%service_integration_url%"]
        calls:
          - [setLogger, ['@logger']]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    ogam.challengeresponseencoder:
        class: OGAMBundle\Services\ChallengeResponseEncoder
        arguments: 
            session: "@session"
            logger: "@logger"
            
    ogam.configurationmanager:
        class: OGAMBundle\Services\ConfigurationManager
        arguments:
            em: "@doctrine.orm.entity_manager"
            logger: "@logger"
                       
