# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    ogam.challenge_response_encoder:
        class: OGAMBundle\Services\ChallengeResponseEncoder
        arguments: 
            session: "@session"
            logger: "@logger"
            
    ogam.configuration_manager:
        class: OGAMBundle\Services\ConfigurationManager
        arguments:
            em: "@doctrine.orm.entity_manager"
            logger: "@logger"
            
    # Repositories not linked to a specific entity
    ogam.generic_repository:
        abstract: true
        class: OGAMBundle\Repository\GenericRepository
        arguments: ["@doctrine.orm.entity_manager"]
        
    ogam.repository.database.metadata:
        parent: ogam.generic_repository
        class: OGAMBundle\Repository\Database\MetadataRepository

    ogam.repository.database.postgresql:
        parent: ogam.generic_repository
        class: OGAMBundle\Repository\Database\PostgresqlRepository                      