# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


    # Service used to encode a challenge for the user login
    ogam.challenge_response_encoder:
        class: OGAMBundle\Services\ChallengeResponseEncoder
        arguments: 
            session: "@session"
            logger: "@logger"
            
    # Service used to read the application parameters from the database
    ogam.configuration_manager:
        class: OGAMBundle\Services\ConfigurationManager
        arguments:
            em: "@doctrine.orm.entity_manager"
            logger: "@logger"
            
    # Listener for the user locale
    ogam.locale_listener:
        class: OGAMBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }
            
    # Repositories not linked to a specific entity
    ogam.generic_repository:
        abstract: true
        class: OGAMBundle\Repository\GenericRepository
        arguments: ["@doctrine.orm.entity_manager"]
        
    ogam.repository.database.metadata:
        parent: ogam.generic_repository
        class: OGAMBundle\Repository\Database\MetadataRepository

    ogam.repository.database.postgresql:
        parent: ogam.generic_repository
        class: OGAMBundle\Repository\Database\PostgresqlRepository                      