<?php
/**
 * Project documents.
 * @package views
 */
?>

<h1>
   Project documents
</h1>

<div class="content">
<br/>

<h2>Presentations</h2>
<ul>
	<li>
		<a href="<?php echo PATH_BASE_URL."/pdf/Project_General_Presentation.ppt"?>" class="pagelink" >Projet General Presentation</a>
	</li>
	<li>
		<a href="<?php echo PATH_BASE_URL."/pdf/SC1_SC2_Presentation.ppt"?>" class="pagelink" >SC 1 &amp; SC 2 Technical Presentation</a>
	</li>
</ul>

<br/>

<h2>Contracts</h2>
<ul>
	<li>
	<a href="<?php echo PATH_BASE_URL."/pdf/Consortium_agreement_NFI_n2008-CPA-1-144.pdf"?>" class="pagelink" >Consortium Agreement</a>
	</li>
	<li>
	<a href="<?php echo PATH_BASE_URL."/pdf/Framework_Contract.pdf"?>" class="pagelink" >Framework Contract</a>
	</li>
	<li>
	<a href="<?php echo PATH_BASE_URL."/pdf/SpecificContract1.pdf"?>" class="pagelink" >Specific Contract 1</a>
	</li>
	<li>
	<a href="<?php echo PATH_BASE_URL."/pdf/SpecificContract2.pdf"?>" class="pagelink" >Specific Contract 2</a>
	</li>
	<li>
	<a href="<?php echo PATH_BASE_URL."/pdf/SpecificContract3.pdf"?>" class="pagelink" >Specific Contract 3</a>
	</li>
	<li>
	<a href="<?php echo PATH_BASE_URL."/pdf/SpecificContract4_Proposal.pdf"?>" class="pagelink" >Specific Contract 4 Proposal</a>
	</li>
	<li>
	<a href="<?php echo PATH_BASE_URL."/pdf/SC5_Proposal.pdf"?>" class="pagelink" >Specific Contract 5 Proposal</a>
	</li>
</ul>



</div>