<?php
/**
 * Project manuals.
 * @package views
 */
?>

<h1>
   Project manuals
</h1>

<div class="content">
    <ul>
        <li>
            <a href="<?php echo PATH_BASE_URL."/pdf/UserManual_QueryModule.pdf"?>" class="pagelink" >User manual for the query module</a>
        </li>
        
        <li>
            <a href="<?php echo PATH_BASE_URL."/pdf/UserManual_IntegrationModule.pdf"?>" class="pagelink" >User manual for the integration module</a>
        </li>
        
        <li>
            <a href="<?php echo PATH_BASE_URL."/pdf/Metadata_Administrator_Manual.pdf"?>" class="pagelink" >Metadata administration manual</a>
        </li>
        
    </ul>
</div>

