<?php
/**
 * Project meetings.
 * @package views
 */
?>

<h1>
   Project meetings
</h1>

<div class="content">
<br/>


	<h2>2009/09/10 Ispra Meeting</h2>
    <ul>
    <li>
		<a href="<?php echo PATH_BASE_URL."/pdf/Meetings/Ispra/20090910Minutes.pdf"?>" class="pagelink" >Progress Meeting</a>
	</li>	
	</ul>
	
	<h2>2009/10/07 Nogent-sur-Vernisson Meeting</h2>
    <ul>
    <li>
		<a href="<?php echo PATH_BASE_URL."/pdf/Meetings/Nogent/20091007Minutes.pdf"?>" class="pagelink" >Thematic Officiers Meeting</a>
	</li>
	</ul>
	
	<h2>2010/01/14 Vienna Meeting</h2>
    <ul>    
    <li>
		<a href="<?php echo PATH_BASE_URL."/pdf/Meetings/Vienna/Meeting_Minutes.pdf"?>" class="pagelink" >Meeting Minutes</a>
	</li>
	<li>
		<a href="<?php echo PATH_BASE_URL."/pdf/Meetings/Vienna/SC3_Introduction.pdf"?>" class="pagelink" >SC3 - Introduction</a>
	</li>
	<li>
		<a href="<?php echo PATH_BASE_URL."/pdf/Meetings/Vienna/Data_Upload.pdf"?>" class="pagelink" >SC3 - Data upload</a>
	</li>
    <li>
		<a href="<?php echo PATH_BASE_URL."/pdf/Meetings/Vienna/lanz-sampling-designs.pdf"?>" class="pagelink" >SC3 - Approaches to data analysis</a>
	</li>
	<li>
		<a href="<?php echo PATH_BASE_URL."/pdf/Meetings/Vienna/Aggregation_and_Interpolation_Module.pdf"?>" class="pagelink" >SC2 - Aggregation and interpolation module</a>
	</li>
	</ul>
	
	<h2>2009/09/10 Ispra Meeting</h2>
    <ul>
    <li>
		<a href="<?php echo PATH_BASE_URL."/pdf/Meetings/Ispra/20100128Minutes.pdf"?>" class="pagelink" >Progress Meeting</a>
	</li>	
	</ul>
	
	
	<h2>2010/03/24 Birmensdorf Meeting</h2>
	<ul>
	<li>
		<a href="<?php echo PATH_BASE_URL."/pdf/Meetings/Birmensdorf/Birmensdorf_Minutes.pdf"?>" class="pagelink" >Meeting Minutes</a>
	</li>
	<li>
		<a href="<?php echo PATH_BASE_URL."/pdf/Meetings/Birmensdorf/Birmensdorf_Meeting_Introduction.pdf"?>" class="pagelink" >Meeting Introduction</a>
	</li>
	<li>
		<a href="<?php echo PATH_BASE_URL."/pdf/Meetings/Birmensdorf/Domains_Lanz.pdf"?>" class="pagelink" >Roles of domain variables</a>
	</li>
	<li>
		<a href="<?php echo PATH_BASE_URL."/pdf/Meetings/Birmensdorf/SC3_Data_Presentation.pdf"?>" class="pagelink" >SC3 - Data presentation</a>
	</li>
	<li>
		<a href="<?php echo PATH_BASE_URL."/pdf/Meetings/Birmensdorf/SC3_Deliverables.pdf"?>" class="pagelink" >SC3 - Deliverables</a>
	</li>
	<li>
		<a href="<?php echo PATH_BASE_URL."/pdf/Meetings/Birmensdorf/Partitioning_Plots.pdf"?>" class="pagelink" >SC3 - Partitioning Plots</a>
	</li>
	<li>
		<a href="<?php echo PATH_BASE_URL."/pdf/Meetings/Birmensdorf/Foret_Map_Validation.pdf"?>" class="pagelink" >SC5 - Forest map validation</a>
	</li>
	<li>
		<a href="<?php echo PATH_BASE_URL."/pdf/Meetings/Birmensdorf/SC7_Lanz.pdf"?>" class="pagelink" >SC7 - Enhancing estimation procedures</a>
	</li>
	
	</ul>
	
	
</div>

