<?php
/**
 * Default layout
 * @package layouts
 */
?>

<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <?php echo $this->headTitle() ?>
  <?php echo $this->headMeta() ?>
  <?php echo $this->headLink() ?>
  <?php echo $this->headStyle() ?>
  <?php echo $this->headScript() ?>
  <script type="text/javascript">
      // Firebugx.js
      if (!window.console /*|| !console.firebug*/)
      {
          var names = ["log", "debug", "info", "warn", "error", "assert", "dir", "dirxml",
          "group", "groupEnd", "time", "timeEnd", "count", "trace", "profile", "profileEnd"];

          window.console = {};
          for (var i = 0; i < names.length; ++i)
              window.console[names[i]] = function() {}
      }
  </script>
  <script type="text/javascript">
      //Defines the base URL for the scripts
     function sendMail(){
        pre='<?= $this->contactEmailPrefix; ?>';
        suf='<?= $this->contactEmailSufix; ?>';
        document.getElementById('lkContact').href="mailto:" + pre + "@" + suf;
      }
  </script>
</head> 
<body>

<div id="wrapper" class="wrapper">

<div id="main-body-bg" class="main-body-bg"></div>
<div id="main-body" class="main-body">
    <!-- HEADER -->
    <div class="header" id="header">
   
        <div id="banner" class="banner">
            <img border="0" alt="Banner" src="<?= $this->baseUrl('img/banner.jpg');?>"/>
        </div>

        <div id="top" class="top">

        <div id="header-beadcrumb" class="header-beadcrumb" style="float:left">
            <span class="pathway">
            <a href="<?= $this->url(array('controller'=>'index'), 'default', true) ?>" ><b><?= $this->translate('Layout Pathway Home') ?></b></a>
            <?php
                $website_session = new Zend_Session_Namespace('website');
                $moduleName = $website_session->module;
                $moduleLabel = $website_session->moduleLabel;
                $moduleURL = $website_session->moduleURL;
                if (!empty($moduleName)) {
                    echo '<img src="'.$this->baseUrl('/img/arrow.png').'"/>';
                    echo '<a href="'. $this->url(array('controller'=>$moduleURL), 'default', true) .'" ><b>'.$this->translate($moduleLabel).'</b></a>';
                }
            ?>
            </span>
        </div>
   

        <div id="header-login" class="header-login" style="float: right">
<?php
        $configuration = Zend_Registry::get("configuration");
        if ($configuration->autoLogin != 1) {
	        $userSession = new Zend_Session_Namespace('user');
	        $user = $userSession->user;
	        if (!empty($user)) {
	             ?>
	             <a href="<?= $this->url(array('controller'=>'user', 'action'=>'show-change-password'), 'default', true) ?>" ><?=$this->translate('Change Password');?></a>
	             &nbsp;
	             <a href="<?= $this->url(array('controller'=>'user', 'action'=>'logout'), 'default', true) ?>" ><?=$this->translate('Log out');?></a>
	<?php
	         } else {
	            ?><a href="<?= $this->url(array('controller'=>'user', 'action'=>'index'), 'default', true) ?>" ><?=$this->translate('Log in');?></a>
	<?php
	         }
        }
?>
        </div>
     </div>

<!-- Fin du header -->
</div>

    <!-- CONTENT -->
    <div class="content" id="content">
        <?= $this->layout()->content ?>
    </div>

<!-- Fin du main-body -->
</div>

    <!-- Utilisé pour maintenir le bas de page en bas -->
    <div id="push" class="push"></div> 

<!-- Fin du wrapper -->
</div>

<div class="footer"  id="footer">
    <div id="footer-ct" class="footer-ct">
        <?= $this->translate('Layout Copyright');?>&nbsp;
        <a id="lkContact" onclick="sendMail();" href="#"><?=$this->translate('Contact Us');?></a>
    </div>
</div>

</body>
</html>