<?php
/**
 * View for the creation of a new data.
 * @package views
 */
?>


<h1>
   Data edition module
</h1>

<div class="select-dataset-form">

<!-- Rappel des infos sur les tables parentes -->
<!-- Lien pour l'édition des tables parents -->

<!-- Affichage du formulaire d'édition -->
<!--  Les élements faisant partie de la clé sont grisés -->
<!--  Les autres valeurs sont éditables -->
<fieldset>
<legend><?= $this->tableFormat->format;?></legend>
<?= $this->form ?>
</fieldset>
<!-- Affichage les tables enfant (uniquement les valeurs de la clé) -->
<!-- Lien vers l'édition d'un enfant existant -->
<!-- Lien pour l'ajout d'un nouvel enfant -->


<!-- Sur chaque lien, alerte javascript proposant la sauvegarde des modifs -->

</div>
