<?php
/**
 * View for the creation of a new data.
 * @package views
 */
?>
<script type="text/javascript" src="<?= $this->baseUrl('js/extjs/ext-all-debug.js') ?>"></script>
<!-- Production mode start
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/genapp.pack-min.js') ?>"></script>
Production mode end --> 

<!-- Debug mode start -->
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/widgets/EditionPanel.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/widgets/EditionFormPanel.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/widgets/FieldForm.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/widgets/form/DateRangeField.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/widgets/form/NumberRangeField.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/widgets/form/TwinNumberField.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/widgets/form/GeometryField.js') ?>"></script>
<!-- Debug mode end -->

<!-- Translations -->
<?php $locale = Zend_Registry::get('Zend_Locale'); ?>
<script type="text/javascript" src="<?= $this->baseUrl('js/extjs/src/locale/ext-lang-'.$locale.'.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/locale/genapp-lang-'.$locale.'.js') ?>"></script>

<!-- Conf genapp -->
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp.conf.js') ?>"></script>

<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('js/extjs/resources/css/ext-all.css') ?>" />

<!-- Gray extend theme -->
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('js/extjs/resources/css/xtheme-gray-extend.css') ?>" />
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('js/genapp/resources/css/genapp-gray-extend-all.css') ?>" />

<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('js/extjsux/basiccheckbox/BasicCheckBox.css') ?>" />
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('css/extjsux.css') ?>" />

<script type="text/javascript">
    Ext.onReady(function(){
    	Genapp.base_url = "<?= $this->baseUrl(); ?>/";

    	// Add the local class to the body
        Ext.getBody().addClass(Genapp.config.localCls);

        // Activate the tooltips system
        // Init the singleton.  Any tag-based quick tips will start working.
        Ext.QuickTips.init();

        // Apply a set of config properties to the singleton
        Ext.apply(Ext.QuickTips.getQuickTip(), {
            showDelay: 250,
            dismissDelay: 0,
            trackMouse: true
        });

        // Turn on validation errors beside the field globally
        Ext.form.Field.prototype.msgTarget = 'qtip'; // The side option poses problems rendering in IE7

        // Set the form label separator
        Ext.layout.FormLayout.prototype.labelSeparator = ' :';

        // Set the blank image to a local one
        Ext.BLANK_IMAGE_URL = Genapp.base_url + "img/s.gif";
        
        // Set the default timeout for AJAX calls
        // The JS timeout must be inferior or equal to the PHP execution time to avoid the not catchable php timeout fatal error
        Ext.Ajax.timeout = 30000;

        Genapp.editionPanel = new Genapp.EditionPanel();
        
	    var win = new Ext.Window({
	           width:500,
	           id:'win',
	           height:500,
	           title:'Edit data',
	           items:[Genapp.editionPanel]
	       });
	       win.show();

    	
    });
</script>

<div id='page'></div>

<!-- Fields required for history management -->
<form id="history-form" class="x-hidden">
    <input type="hidden" id="x-history-field" />
    <iframe id="x-history-frame"></iframe>
</form>




<h1>
<?php
if ($this->mode == 'ADD') {
	echo 'Add '.$this->tableFormat->label;
} else {
	echo 'Edit '.$this->tableFormat->label;
}
?>
</h1>


<!-- Rappel des infos sur les tables parentes -->
<!-- Lien pour l'édition des tables parents -->
<fieldset>
<legend>Parents summary</legend>
<?php
$ancestors = array_reverse($this->ancestors);
foreach ($ancestors as $ancestor) {
	echo $this->generateEditLink($ancestor)."<br/>";
}

?>
</fieldset>

<div class="select-dataset-form">

<!-- Affichage du formulaire d'édition -->
<!--  Les élements faisant partie de la clé sont grisés -->
<!--  Les autres valeurs sont éditables -->
<fieldset>
<legend><?= $this->tableFormat->label; ?></legend>
<?= $this->form ?>
</fieldset>



<!-- Affichage les tables enfant (uniquement les valeurs de la clé) -->
<!-- Lien vers l'édition d'un enfant existant -->
<!-- Lien pour l'ajout d'un nouvel enfant -->
<?php
if (!empty($this->children)) {
?>
<fieldset>
<legend>Children summary</legend>
<?php
	// Iterate though the child tables
	foreach ($this->children as $childFormat => $childrenLines) {

		echo "<fieldset><legend>".$this->childrenTableLabels[$childFormat]."</legend>";

		// Add the edit links for each child of the current item
		foreach ($childrenLines as $child) {
			echo $this->generateEditLink($child)."<br/>";
		}

		// Add link to a new child
		$data = clone $this->data;
		$data->tableFormat->format = $childFormat;
		echo $this->generateAddLink($data, $this->childrenTableLabels[$childFormat])."<br/>";

		echo "</fieldset>";
	}
?>
</fieldset>
<?php } ?>

</div>

<br/>
<?php

if (empty($this->children)) {
	// If the item has no child we can delete it
	echo $this->generateDeleteLink($this->data);
} else {
	echo '<img src="'.$this->baseUrl('img/bin.gif').'" /> Delete data (not available because of children)';
}

?>


<div class="message">
<?= $this->message ?>
</div>