<?php
/**
 * View for the creation of a new data.
 * @package views
 */
?>


<h1>
<?php
if ($this->mode == 'ADD') {
	echo 'Add '.$this->tableFormat->format;
} else {
	echo 'Edit '.$this->tableFormat->format;
}
?>
</h1>


<!-- Rappel des infos sur les tables parentes -->
<!-- Lien pour l'édition des tables parents -->
<fieldset>
<legend>Parents summary</legend>
<?php
$ancestors = array_reverse($this->ancestors);
foreach ($ancestors as $ancestor) {
	$tableFormat = $ancestor->tableFormat;
	// Build the URL to link to the parent items
	$urlArray = array('controller' => 'dataedition', 'action' => 'show-edit-data');
	$urlArray['FORMAT'] = $tableFormat->format;
	foreach ($ancestor->infoFields as $tableField) {
		$urlArray[$tableField->data] = $tableField->value;
	}
	echo '<a href="'.$this->url($urlArray, null, true).'">Edit '.$tableFormat->format.'</a><br>';
}

?>
</fieldset>

<div class="select-dataset-form">

<!-- Affichage du formulaire d'édition -->
<!--  Les élements faisant partie de la clé sont grisés -->
<!--  Les autres valeurs sont éditables -->
<fieldset>
<legend><?= $this->tableFormat->format; ?></legend>
<?= $this->form ?>
</fieldset>
<!-- Affichage les tables enfant (uniquement les valeurs de la clé) -->
<!-- Lien vers l'édition d'un enfant existant -->
<!-- Lien pour l'ajout d'un nouvel enfant -->


<!-- Sur chaque lien, alerte javascript proposant la sauvegarde des modifs -->

</div>
