<?php
/**
 * Default view for the data edition module.
 * @package views
 */
?>

<h1>
   Data edition module
</h1>

<div class="left-column">
<div class="moduletable_menu">

<ul id="appmenu" class="menu">

<?
$user_session = new Zend_Session_Namespace('user');
$role = $user_session->role;
?>

<li>
<!-- TODO : Remove hardcoded values when a selection screen is available -->
<a href="<?= $this->url(array('controller'=>'dataedition',
				'action'=>'show-edit-data', 
				'SCHEMA'=>'RAW_DATA', 
				'FORMAT' => 'SPECIES_DATA',
				'PROVIDER_ID' => '1',
				'PLOT_CODE' => '21573-F1000-6-6T',
				'CYCLE' => '5',
				'SPECIES_CODE' => '031.001.041'
				), 'default', true) ?>">Edit data</a>
				
</li>



</ul>
</div>
</div>

<div class="message">
<?= $this->message ?>
</div>
