<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */

/**
 * View for the parsing of PDF files.
 * @package views
 */
?>

<H1><?= $this->translate('File Content');?></H1>

<div class="password-change-user-name">
    <?=$this->translate('Content of the file:');?>&nbsp;<b><?=$this->file?></b>
</div>

<p class="file_contents"><?= $this->content;?></p>

<p class="subTableLink">
    <a href="<?= $this->url(array('controller'=>'indexedpdffile', 'action'=>'list', 'INDEX_KEY'=>$this->indexKey), 'default', true) ?>"><?= $this->translate('Back');?></a>
</p>