<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */

/**
 * Default layout
 * @package layouts
 */
?>

<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <?php echo $this->headTitle() ?>
  <?php echo $this->headMeta() ?>
  <?php echo $this->headLink() ?>
  <?php echo $this->headStyle() ?>
  <?php echo $this->headScript() ?>
  <link rel="shortcut icon" href="<?php echo $this->baseUrl('favicon.ico');?>" />
  <script type="text/javascript">
      // Firebugx.js
      if (!window.console /*|| !console.firebug*/)
      {
          var names = ["log", "debug", "info", "warn", "error", "assert", "dir", "dirxml",
          "group", "groupEnd", "time", "timeEnd", "count", "trace", "profile", "profileEnd"];

          window.console = {};
          for (var i = 0; i < names.length; ++i)
              window.console[names[i]] = function() {}
      }
  </script>
  <script type="text/javascript">
      //Defines the base URL for the scripts
     function sendMail(){
        pre='<?php echo $this->contactEmailPrefix; ?>';
        suf='<?php echo $this->contactEmailSufix; ?>';
        document.getElementById('lkContact').href="mailto:" + pre + "@" + suf;
      }
  </script>
</head>
<body>

<div id="wrapper" class="wrapper">

<div id="main-body-bg" class="main-body-bg"></div>
<div id="main-body" class="main-body">
    <!-- HEADER -->
    <div class="header" id="header">

        <div id="banner" class="banner">
            <img border="0" alt="Banner" src="<?php echo $this->baseUrl('img/banner.jpg');?>"/>
        </div>

        <div id="top" class="top">

	        <div id="header-beadcrumb" class="header-beadcrumb" style="float: left">
			   <?php
			   $request = Zend_Controller_Front::getInstance()->getRequest();
			   $controllerName = $request->getControllerName();
			   $actionName = $request->getActionName();
			   $moduleName = $request->getModuleName();

			   $breadcrumb = $this->navigation()
			         ->breadcrumbs()
			         ->setLinkLast(false)
			         ->setMinDepth(0)
			         ->setSeparator('<img src="/img/arrow.png">')
			         ->render();
			   if ($breadcrumb) {
			      echo $breadcrumb;
			   } else {

			      $topControllerPage = $this->navigation()->findOneBy('controller', $controllerName);
			      if ($topControllerPage) {
			         $currentPage = Zend_Navigation_Page::factory(array(
			               'label' => 'Page',
			               'action' => $actionName,
			               'controller' => $controllerName,
			               'module' => $moduleName,
			         ));
			         $topControllerPage->addPage($currentPage);
			         echo $this->navigation()
			               ->breadcrumbs()
			               ->setMinDepth(0)
			               ->setMaxDepth(1)// Don't show current page link (we don(t know its name)
			               ->setLinkLast(true)// and then lats link is top controller page, clickable
			               ->setSeparator('<img src="/img/arrow.png">')
			               ->render();
			      }
			   }
			   ?>
	        </div>

        <div id="header-login" class="header-login" style="float: right">
<?php
        $configuration = Zend_Registry::get("configuration");
        $language_flags[] = $configuration->getConfig('language_flags1', 'fr');
        $language_flags[] = $configuration->getConfig('language_flags2', 'en');

        if (!empty($language_flags)) {
            foreach($language_flags as $flag){
                if(!empty($flag) && ($flag !== $this->locale)) {
                  // Building of the uri
                  $uri = $this->url().'?lang='.$flag;
                  $params = $this->userAgent()->getServerValue('query_string');
                  // Deletion of the previous lang parameter if present
                  $paramsArray = explode('&',$params);
                  foreach ($paramsArray as $key => $value) {
                    $param = explode('=',$value);
                    if($param[0] === 'lang')  unset($paramsArray[$key]);
                  }
                  $params = implode("&", $paramsArray);
                  // Addition of the page current parameters
                  if(!empty($params)) $uri .= '&'.$params;
                  // Creation of the html link
                  echo '<a href="'.$uri.'" ><div class="'.$flag.'-flag" title="'.$this->translate('Translate this site '.$flag).'">&nbsp;</div></a>';
                }
            }
        }

        $autoLogin = $configuration->getConfig('autoLogin', false) == 1;
        if (!$autoLogin) {
	        $userSession = new Zend_Session_Namespace('user');
	        $user = $userSession->user;
	        if (!empty($user)) {
	             ?>
	             <a href="<?php echo $this->url(array('controller'=>'user', 'action'=>'show-change-password'), 'default', true) ?>" ><?php echo $this->translate('Change Password');?></a>
	             &nbsp;
	             <a id="logoutLink" href="<?php echo $this->url(array('controller'=>'user', 'action'=>'logout'), 'default', true) ?>" ><?php echo $this->translate('Log out');?></a>
	<?php
	         } else {
	            ?><a href="<?php echo $this->url(array('controller'=>'user', 'action'=>'index'), 'default', true) ?>" ><?php echo $this->translate('Log in');?></a>
	<?php
	         }
        }
?>
        </div>
     </div>

<!-- Fin du header -->
</div>

    <!-- CONTENT -->
    <div class="content" id="content">
        <?php echo $this->layout()->content ?>
    </div>

<!-- Fin du main-body -->
</div>

    <!-- Utilisé pour maintenir le bas de page en bas -->
    <div id="push" class="push"></div>

<!-- Fin du wrapper -->
</div>

<div class="footer"  id="footer">
    <div id="footer-ct" class="footer-ct">
    	<span title="Build @build_number@">Version @version_number@&nbsp;-&nbsp;</span>
        <?php echo $this->translate('Layout Copyright');?>&nbsp;
        <a id="lkContact" onclick="sendMail();" href="#"><?php echo $this->translate('Contact Us');?></a>
    </div>
</div>

</body>
</html>