<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */


/**
 * Show the roles of the web site.
 * @package views
 */
?>
<h1>
   <?=$this->translate('Roles');?>
</h1>


<table class="sectiontable">
<tr>
	<th></th>
	<th><?=$this->translate('Code');?></th>
	<th><?=$this->translate('Label');?></th>
	<th><?=$this->translate('Definition');?></th>
	<th></th>
</tr>
<?
$i = 0;
foreach ($this->roles as $role) {
?>
<tr class="sectiontableentry<?=$i % 2?>">
	<td class="edit-cell"><a title="<?=$this->translate('Edit');?>" href="<?= $this->url(array('controller'=>'usermanagement','action'=>'show-edit-role'), null, true)?>?roleCode=<?=$role->roleCode;?>"></a></td>
	<td><?= $this->escape($role->roleCode); ?></td>
	<td><?= $this->escape($role->roleLabel); ?></td>
	<td><?= $this->escape($role->roleDefinition); ?></td>
	<td class="delete-cell"><a title="<?=$this->translate('Delete');?>" href="<?= $this->url(array('controller'=>'usermanagement','action'=>'delete-role'), null, true)?>?roleCode=<?=$role->roleCode;?>" onClick="return confirm('<?=$this->translate('Are you sure?')?>');"></a></td>
</tr>
<?
	$i++;
}
?>
</table>
 
<p class="subTableLink">
    <a href="<?= $this->url(array('controller'=>'usermanagement','action'=>'show-create-role'), null, true) ?>"><?=$this->translate('Create Role');?></a>
<p/>

 