<?php
/**
 * Default view for the user management module.
 * @package views
 */
?>

<h1>
   User Management Module
</h1>

<div class="left-column">
<div class="moduletable_menu">
<h3>
    Select a menu
</h3>
<ul id="appmenu" class="menu">

<li>
<a href="<?= $this->url(array('controller'=>'usermanagement','action'=>'show-users'), null, true) ?>">Show the users</a>
</li>

<li>
<a href="<?= $this->url(array('controller'=>'usermanagement','action'=>'show-roles'), null, true) ?>">Show the roles</a>
</li>

</div>
</div>
