<?php
/**
 * Show the roles of the web site.
 * @package views
 */
?>
<h1>
   <?=$this->translate('Roles');?>
</h1>


<table class="sectiontable">
<tr>
	<th></th>
	<th><?=$this->translate('Code');?></th>
	<th><?=$this->translate('Label');?></th>
	<th><?=$this->translate('Definition');?></th>
	<th></th>
</tr>
<?
$i = 0;
foreach ($this->roles as $role) {
?>
<tr class="sectiontableentry<?=$i % 2?>">
	<td class="edit-cell"><a title="<?=$this->translate('Edit');?>" href="<?= $this->url(array('controller'=>'usermanagement','action'=>'show-edit-role'), null, true)?>?roleCode=<?=$role->roleCode;?>"></a></td>
	<td><?= $this->escape($role->roleCode); ?></td>
	<td><?= $this->escape($role->roleLabel); ?></td>
	<td><?= $this->escape($role->roleDefinition); ?></td>
	<td class="delete-cell"><a title="<?=$this->translate('Delete');?>" href="<?= $this->url(array('controller'=>'usermanagement','action'=>'delete-role'), null, true)?>?roleCode=<?=$role->roleCode;?>" onClick="return confirm('<?=$this->translate('Are you sure?')?>');"></a></td>
</tr>
<?
	$i++;
}
?>
</table>
 
<p class="subTableLink">
    <a href="<?= $this->url(array('controller'=>'usermanagement','action'=>'show-create-role'), null, true) ?>"><?=$this->translate('Create Role');?></a>
<p/>

 