<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */


/**
 * Show the users of the web site.
 * @package views
 */
?>
<h1>
   <?=$this->translate('Users');?>
</h1>


<table class="sectiontable">
<tr>
	<th></th>
	<th></th>
	<th><?=$this->translate('User Login');?></th>
	<th><?=$this->translate('User Name');?></th>
	<th><?=$this->translate('Provider');?></th>
	<th><?=$this->translate('Email');?></th>
	<th><?=$this->translate('Role');?></th>
	<th></th>
</tr>
<?php
$i = 0;
foreach($this->users as $user) {
?>
<tr class="sectiontableentry<?=$i % 2?>">
	<td class="edit-cell"><a title="<?=$this->translate('Edit');?>" href="<?= $this->url(array('controller'=>'usermanagement','action'=>'show-edit-user'), null, true)?>?userLogin=<?=$user->login;?>">&nbsp;</a></td>
	<td class="change-password-cell"><a title="<?=$this->translate('Change Password');?>" href="<?= $this->url(array('controller'=>'usermanagement','action'=>'show-change-password'), null, true)?>?userLogin=<?=$user->login;?>">&nbsp;</a></td>
	<td><?= $this->escape($user->login); ?></td>
	<td><?= $this->escape($user->username); ?></td>
	<td><?= $this->providers[$user->providerId]; ?></td>
	<td><?= $this->escape($user->email); ?></td>
	<td><?= $this->escape($user->role->label); ?></td>
	<td class="delete-cell"><a title="<?=$this->translate('Delete');?>" href="<?= $this->url(array('controller'=>'usermanagement','action'=>'delete-user'), null, true)?>?userLogin=<?=$user->login;?>" onClick="return confirm('<?=$this->translate('Are you sure?')?>');">&nbsp;</a></td>
</tr>
<?php
$i++;
}
?>
</table>
 
<p class="subTableLink">
    <a href="<?= $this->url(array('controller'=>'usermanagement','action'=>'show-create-user'), null, true) ?>"><?=$this->translate('Create User');?></a>
<p/>

 