<?php
/**
 * Show the users of the web site.
 * @package views
 */
?>
<h1>
   <?=$this->translate('Users');?>
</h1>


<table class="sectiontable">
<tr>
	<th><?=$this->translate('Edit User');?></th>
	<th><?=$this->translate('Change Password');?></th>
	<th><?=$this->translate('User Login');?></th>
	<th><?=$this->translate('User Name');?></th>
	<th><?=$this->translate('Country');?></th>
	<th><?=$this->translate('Email');?></th>
	<th><?=$this->translate('Role');?></th>
	<th><?=$this->translate('Delete');?></th>
</tr>
<?
$i = 0;
foreach($this->users as $user) {
?>
<tr class="sectiontableentry<?=$i % 2?>">
	<td><a href="<?= $this->url(array('controller'=>'usermanagement','action'=>'show-edit-user'), null, true)?>?userLogin=<?=$user->login;?>"><?=$this->translate('Edit');?></a></td>
	<td><a href="<?= $this->url(array('controller'=>'usermanagement','action'=>'show-change-password'), null, true)?>?userLogin=<?=$user->login;?>"><?=$this->translate('Change Password');?></a></td>
	<td><?= $this->escape($user->login); ?></td>
	<td><?= $this->escape($user->username); ?></td>
	<td><?= $this->providers[$user->providerId]; ?></td>
	<td><?= $this->escape($user->email); ?></td>
	<td><?= $this->escape($user->roleLabel); ?></td>
	<td><a href="<?= $this->url(array('controller'=>'usermanagement','action'=>'delete-user'), null, true)?>?userLogin=<?=$user->login;?>" onClick="return confirm('Are you sure?');"><?=$this->translate('Delete');?></a></td>
</tr>
<?
$i++;
}
?>
</table>
 
<p class="subTableLink">
    <a href="<?= $this->url(array('controller'=>'usermanagement','action'=>'show-create-user'), null, true) ?>"><?=$this->translate('Create User');?></a>
<p/>

 