<?php
/**
 * Show the roles of the web site.
 * @package views
 */
?>
<h1>
   <?=$this->translate('Roles');?>
</h1>


<table class="sectiontable">
<tr>
	<th><?=$this->translate('Edit');?></th>
	<th><?=$this->translate('Code');?></th>
	<th><?=$this->translate('Label');?></th>
	<th><?=$this->translate('Definition');?></th>
	<th><?=$this->translate('Delete');?></th>
</tr>
<?
$i = 0;
foreach ($this->roles as $role) {
?>
<tr class="sectiontableentry<?=$i % 2?>">
	<td><a href="<?= $this->url(array('controller'=>'usermanagement','action'=>'show-edit-role'), null, true)?>?roleCode=<?=$role->roleCode;?>"><?=$this->translate('Edit');?></a></td>
	<td><?= $this->escape($role->roleCode); ?></td>
	<td><?= $this->escape($role->roleLabel); ?></td>
	<td><?= $this->escape($role->roleDefinition); ?></td>
	<td><a href="<?= $this->url(array('controller'=>'usermanagement','action'=>'delete-role'), null, true)?>?roleCode=<?=$role->roleCode;?>" onClick="return confirm('Are you sure?');"><?=$this->translate('Delete');?></a></td>
</tr>
<?
	$i++;
}
?>
</table>
 
<p class="subTableLink">
    <a href="<?= $this->url(array('controller'=>'usermanagement','action'=>'show-create-role'), null, true) ?>"><?=$this->translate('Create Role');?></a>
<p/>

 