<?php
/**
 * Default view for the integration module.
 * @package views
 */
?>

<h1>
   <?=$this->translate('Data integration module');?>
</h1>

<div class="left-column">
<div class="moduletable_menu">

<ul id="appmenu" class="menu">

<?
$user_session = new Zend_Session_Namespace('user');
$role = $user_session->role;
?>


<li>
<a href="<?= $this->url(array('controller'=>'integration','action'=>'show-data-submission-page'), null, true) ?>"><?=$this->translate('Submit Data');?></a>
</li>

</ul>
</div>
</div>

