<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */


/**
 * View for the data submission.
 * @package views
 */
?>
<script type="text/javascript" src="<?php echo  $this->baseUrl('js/progressbar.js') ?>"></script>
<script type="text/javascript" src="<?php echo  $this->baseUrl('js/extjs/adapter/ext/ext-base.js') ?>"></script>
<script type="text/javascript" src="<?php echo  $this->baseUrl('js/extjs/ext-all.js') ?>"></script>
<script type="text/javascript" src="<?php echo  $this->baseUrl('js/genapp/source/genapp.js') ?>"></script>

<h1>
   <?php echo $this->translate('Data integration module');?>
</h1>

<!-- Show the currently active location submissions -->
<?php if(!empty($this->submissions)){ ?>
<table class="sectiontable">
<tr>
    <th style="text-align:center"><?php echo $this->translate('Submission ID');?></th>
    <th style="text-align:center"><?php echo $this->translate('Date');?></th>
    <th style="text-align:center"><?php echo $this->translate('Provider');?></th>
    <th style="text-align:center"><?php echo $this->translate('User');?></th>
    <th style="text-align:center"><?php echo $this->translate('Dataset');?></th>
    <th style="text-align:center"><?php echo $this->translate('Step');?></th>
    <th style="text-align:center"><?php echo $this->translate('Status');?></th>
    <th><?php echo $this->translate('File');?></th>
    <th style="text-align:right"><?php echo $this->translate('Lines');?>&nbsp;</th>
    <th style="text-align:center"><?php echo $this->translate('Actions');?></th>
    <th></th>
</tr>
<?php

// Get the user permissions
$userSession = new Zend_Session_Namespace('user');
$role = $userSession->user->role;


$i = 0;
foreach ($this->submissions as $submission) {
?>
<tr class="sectiontableentry<?php echo $i % 2?>">
    <td><?php echo  $this->escape($submission->submissionId); ?></td>
    <td><?php echo  $this->escape($submission->date); ?></td>
    <td><?php echo  $this->escape($submission->providerLabel); ?></td>
    <td><?php echo  $this->escape($submission->userLogin); ?></td>
    <td><?php echo  $this->escape($submission->datasetLabel); ?></td>
    <td><?php echo  $this->escape($submission->step); ?></td>
    <td>
            <?php if ($submission->status === "OK" || $submission->status === "CHECKED") : ?>
            	<?php echo  $this->escape($submission->status); ?>
                <img src="<?php echo  $this->baseUrl('img/Green_tick.png') ?>" />
            <?php elseif ($submission->status === "WARNING") : ?>
            	<?php echo  $this->escape($submission->status); ?>
                <img src="<?php echo  $this->baseUrl('img/warning_orange.png') ?>" />
            <?php elseif ($submission->status === "RUNNING") : ?>
                <div class="tempStatusDiv" id="tempStatusDiv_<?php echo  $submission->submissionId ?>">
                <script type="text/javascript">

                // Display the progress bar
                display('progressBar<?php echo  $submission->submissionId ?>', '', 0, '<?php echo  $this->baseUrl('img/') ?>');
                
                // Refresh The status of the submission
                Genapp.util.getStatus_<?php echo  $submission->submissionId ?> =  function (){
                    var url = '<?php echo  $this->baseUrl('Integration/') ?>';
                    <?php if ($submission->step === "CHECKED") : ?>
                        url += 'get-check-status';
                    <?php else : ?>
                        url += 'get-data-status';
                    <?php endif; ?>
                    Ext.Ajax.request({
                       url: url,
                       params:{
                           action:'status',
                           submissionId:<?php echo  $submission->submissionId ?>
                       },
                       callback: function(options, success, response){
                            var rp = Ext.decode(response.responseText);
                            var src = '<?php echo  $this->baseUrl('img/') ?>';
                            switch(rp.status){
                                case 'OK':
                                case 'WARNING':
                                case 'ERROR':
                                case 'CRASH':
                                    Ext.TaskMgr.stop(Genapp.util.getStatusTask_<?php echo  $submission->submissionId ?>);
                                    location.reload();
                                    break;
                                case 'RUNNING':
                                    total = rp.totalCount;
                                    if (total == 0) {
                                    	percentage = 1;
                                    } else {
                                    	percentage = rp.currentCount / total;
                                    }
                                    percentage = (percentage * 100);
                                    setLabel('progressBar<?php echo  $submission->submissionId ?>', rp.taskName);
                                    setProgress('progressBar<?php echo  $submission->submissionId ?>', percentage);
                                    break;
                                default:
                                    return;
                            }
                       }
                    });
                }
                // equivalent using TaskMgr
                Genapp.util.getStatusTask_<?php echo  $submission->submissionId ?> = {
                    run: Genapp.util.getStatus_<?php echo  $submission->submissionId ?>,
                    interval: 2000
                };
                Ext.TaskMgr.start(Genapp.util.getStatusTask_<?php echo  $submission->submissionId ?>);
                </script>
                </div>
            <?php else : //"ERROR" or "CRASH") ?>
            	<?php echo 
		$this->escape($submission->status);
?>
                <img src="<?php echo  $this->baseUrl('img/Red_x.png') ?>" />
            <?php endif; ?>
    </td>
    <td colspan=2>
        <?php if ($submission->status !== "DATARUNNING") : ?>
            <table width="100%">
            <?php foreach ($submission->files as $file) : ?>
                <tr><td class="file-name">
                	<span title="<?php echo  $file->fileType ?>">
                    <?php
                        $fileName = $file->fileName;
                        $fileName = strtr($fileName,'\\','/');
                        $fileName = substr($fileName, strrpos($fileName,'/') + 1);
                        echo $fileName;
                    ?>
                    </span>
                </td>
                <td class="line-number"><?php echo  $file->lineNumber ?></td>
                </tr>
                
            <?php endforeach; ?>
            </table>
        <?php endif; ?>
    </td>
    
    <td>
    <?php
	if ($submission->step === "INSERTED" && $submission->status === "OK") {
?>
    <p><a href="<?php echo  $this->url(array('controller'=>'integration','action'=>'check-submission'), null, true)?>?submissionId=<?php echo $submission->submissionId;?>" ><?php echo $this->translate('Check data');?></a></p>
    <?php }
	if ($submission->step !== "INIT" && $submission->status !== "DATARUNNING") {
?>
    <p><a href="<?php echo  $this->url(array('controller'=>'proxy','action'=>'showreport'), 'default', true)?>?submissionId=<?php echo $submission->submissionId;?>" ><?php echo $this->translate('Show report');?></a></p>
    <?php }
    if ($submission->step === "CHECKED" && ($submission->status === "OK" || $submission->status === "WARNING")) {
?>
    <p><a href="<?php echo  $this->url(array('controller'=>'integration','action'=>'validate-data'), null, true)?>?submissionId=<?php echo $submission->submissionId;?>" onClick="return confirm('<?php echo $this->translate('Confirm_submission_warning');?>');"><?php echo $this->translate('Confirm submission');?></a></p>
    <?php } 
    if ($submission->step != "VALIDATED" || ($role->isAllowed('CANCEL_VALIDATED_SUBMISSION'))) {
    	if ($submission->providerId == $userSession->user->providerId || ($role->isAllowed('CANCEL_OTHER_PROVIDER_SUBMISSION'))) {
?>
    <p><a href="<?php echo  $this->url(array('controller'=>'integration','action'=>'cancel-data-submission'), null, true)?>?submissionId=<?php echo $submission->submissionId;?>" onClick="return confirm('<?php echo $this->translate('Are you sure?');?>');"><?php echo $this->translate('Cancel Submission');?></a></p>
<?php  }
    } ?>        
</td></tr>
<?php
	$i++;
}
?>
</table>
<?php } else { ?>
<div class="no-submission"><?php echo $this->translate('No submission found');?></div>
<?php } ?>
<p class="subTableLink">
    <a href="<?php echo  $this->url(array('controller'=>'integration','action'=>'show-create-data-submission'), null, true) ?>"><?php echo $this->translate('Create data submission');?></a>
</p>
