<h1 style="text-align: center"><?php echo $this->data['title']; ?></h1>
<table style="width: 100%;">
    <tr>
        <td style="width: 50%;border: solid 0.5mm #000000;">
            <img style="width: 100%" src="<?php echo $this->imgPath1; ?>" />
        </td>
        <td style="width: 50%;border: solid 0.5mm #000000;">
            <img style="width: 100%" src="<?php echo $this->imgPath2; ?>" />
        </td>
    </tr>
</table>
<?php foreach ($this->data['formats'] as $format): ?>
<h2><?php echo $format['title']; ?></h2>
<ul>
    <?php foreach ($format['fields'] as $field): ?>
    <li>
        <?php echo $field['label']; ?> :
        <?php if (is_array($field['value'])): ?>
        <?php echo implode(', ', $field['value']); ?>
        <?php else: ?>
        <?php echo $field['value']; ?>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<?php endforeach; ?>