<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */



/**
 * Default view for the data querying module.
 * @package views
 */
?>
  	
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('js/extjs/build/packages/ext-theme-gray/build/resources/ext-theme-gray-all-debug.css') ?>" />
<script type="text/javascript" src="<?= $this->baseUrl('js/extjs/build/ext-all.js') ?>"></script>
<script type="text/javascript">
    Ext.namespace('Ogam');
    Ogam.base_url = "<?= $this->baseUrl('query/..'); ?>/";
    Ogam.ajax_query_url = "<?= $this->baseUrl('query') ?>/";
</script>
<script type="text/javascript">
    Ext.Loader.setConfig({
      enabled: true,
      paths: {
          'GeoExt': '<?= $this->baseUrl('js/GeoExt/src/GeoExt') ?>'
      }
    });
</script>
<script type="text/javascript" src="<?= $this->baseUrl('js/OpenLayers/lib/OpenLayers.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/app/store/request/PredefinedGroup.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/app/view/abstract/Win.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/app/view/map/MapAddonsPanel.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/app/view/map/MapPanel.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/app/view/map/MainWin.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/app/view/request/MainWin.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/app/view/result/MainWin.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/app/view/navigation/MainWin.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/app/view/request/DeprecatedFormPanel.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/app/view/request/ProcessPanel.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/app/view/request/DeprecatedPredefinedRequestWin.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/app/controller/request/DeprecatedForm.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/app/view/navigation/DeprecatedDetailGrid.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/app/view/request/DeprecatedAdvancedRequestWin.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/app/view/Main.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/app/Application.js') ?>"></script>

<div id='page'></div>

<!-- Fields required for history management -->
<form id="history-form" class="x-hidden">
    <input type="hidden" id="x-history-field" />
    <iframe id="x-history-frame"></iframe>
</form>

