<?php
/**
 * View for the creation of a new data.
 * @package views
 */
?>
<script type="text/javascript" src="<?= $this->baseUrl('js/extjs/adapter/ext/ext-base.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/genapp.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/extjs/ext-all-debug.js') ?>"></script>

<!-- Production mode start
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/genapp.pack-min.js') ?>"></script>
< Production mode end --> 

<!-- Debug mode start -->

<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/widgets/FieldForm.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/widgets/CardPanel.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/widgets/form/DateRangeField.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/widgets/form/NumberRangeField.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/widgets/form/TwinNumberField.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/widgets/form/GeometryField.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/widgets/form/TreeField.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/widgets/form/menu/NumberRangeMenu.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/widgets/form/menu/DateRangeMenu.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/widgets/form/menu/TreeMenu.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/widgets/form/picker/NumberRangePicker.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/widgets/form/picker/DateRangePicker.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/widgets/form/picker/TreePicker.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/extjsux/basiccheckbox/BasicCheckBox.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/extjsux/datePatch/datePatchExtjs3.1.1.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/widgets/EditionPanel.js') ?>"></script>

<!-- Debug mode end -->

<!-- Translations -->
<?php $locale = Zend_Registry::get('Zend_Locale'); ?>
<script type="text/javascript" src="<?= $this->baseUrl('js/extjs/src/locale/ext-lang-'.$locale.'.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp/source/locale/genapp-lang-'.$locale.'.js') ?>"></script>

<!-- Conf genapp -->
<script type="text/javascript" src="<?= $this->baseUrl('js/genapp.conf.js') ?>"></script>

<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('js/extjs/resources/css/ext-all.css') ?>" />

<!-- Gray extend theme -->
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('js/extjs/resources/css/xtheme-gray-extend.css') ?>" />
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('js/genapp/resources/css/genapp-gray-extend-all.css') ?>" />

<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('js/extjsux/basiccheckbox/BasicCheckBox.css') ?>" />
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('css/extjsux.css') ?>" />

<script type="text/javascript">
    Ext.onReady(function(){
        Genapp.base_url = "<?= $this->baseUrl('dataedition/..'); ?>/";
        Genapp.ajax_query_url = "<?= $this->baseUrl('dataedition') ?>/";
        if (Genapp.CardPanel) {
            Ext.apply(Genapp.CardPanel.prototype, {
                shownPages : [ 'editionpage' ],
                activeItem : 0,
                widthToSubstract : 100, // 2*50 of margin 
                heightToSubstract : 160 // 120 of header + 30 of footer
            });
        }
        if (Genapp.EditionPanel) {
            Ext.apply(Genapp.EditionPanel.prototype, 
                <?php
                    $patch = array();

                    // unique identifier of the data
                    $patch['dataId'] = $this->dataId;

                    // message
                    if (!empty($this->message)) {
                        $patch['message'] = $this->message;
                    }

                    // mode
                    $patch['mode'] = $this->mode;

                    // parentsLinks
                    $ancestors = array_reverse($this->ancestors);
                    $parentsLinks = '';
                    foreach ($ancestors as $ancestor) {
                        $parentsLinks .= $this->generateEditLink($ancestor) . "<br/>";
                    }
                    if ($parentsLinks !== '') {
                        $patch['parentsLinks'] = $parentsLinks;
                    }
                    // dataTitle
                    $patch['dataTitle'] =  $this->escape($this->tableFormat->label);
                    // disableDeleteButton & deleteButtonTooltip
                    if (empty($this->children)) {
                        // If the item has no child we can delete it
                        $patch['disableDeleteButton'] = false;
                        //$this->generateDeleteLink($this->data);
                    } else {
                        $patch['disableDeleteButton'] = true;
                    }
                    // childrenConfigOptions
                    if (!empty($this->children)) {
                        // Iterate though the child tables
                        $childrenConfigOptions = array();
                        foreach ($this->children as $childFormat => $childrenLines) {
                            $configOptions = array();
                            $configOptions['buttonAlign'] = 'center';
                            $configOptions['title'] = $this->escape($this->childrenTableLabels[$childFormat]);

                            // Add the edit links for each child of the current item
                            $content = '';
                            foreach ($childrenLines as $child) {
                                $content .= $this->generateEditLink($child)."<br/>";
                            }
                            if ($content !== '') {
                                $configOptions['html'] = $content;
                            } else {
                                $content = $this->translate('No %value% found.');
                                $configOptions['html'] = str_replace('%value%', strtolower($this->escape($this->childrenTableLabels[$childFormat])), $content);
                            }

                            // Add link to a new child
                            $configOptions['AddChildURL'] = $this->generateAddLink($this->data->tableFormat->schemaCode, $childFormat, $this->data->infoFields);

                            array_push($childrenConfigOptions, $configOptions);
                        }
                        $patch['childrenConfigOptions'] = $childrenConfigOptions;
                    }
                    echo json_encode($patch);
                ?>
            );
        }
        Genapp.buildApplication();

        Genapp.cardPanel.on('resizewrapper',Genapp.util.resizeWrapper);
    });
</script>

<div id='page'></div>

<!-- Fields required for history management -->
<form id="history-form" class="x-hidden">
    <input type="hidden" id="x-history-field" />
    <iframe id="x-history-frame"></iframe>
</form>