<?php
/**
 * Licensed under EUPL v1.1 (see http://ec.europa.eu/idabc/eupl).
 *
 * © European Union, 2008-2012
 *
 * Reuse is authorised, provided the source is acknowledged. The reuse policy of the European Commission is implemented by a Decision of 12 December 2011.
 *
 * The general principle of reuse can be subject to conditions which may be specified in individual copyright notices.
 * Therefore users are advised to refer to the copyright notices of the individual websites maintained under Europa and of the individual documents.
 * Reuse is not applicable to documents subject to intellectual property rights of third parties.
 */



/**
 * Parameters for the map.
 * @package views
 */
?>
	// This file containts Javascript
	
	
	//
	// Define the map parameters
	// 
	Genapp.map = {};
	
	Genapp.map.defaultzoom = <?php echo  $this->defaultzoom ?>;
	Genapp.map.x_center = <?php echo  $this->centerX ?>;
	Genapp.map.y_center = <?php echo  $this->centerY ?>;
	Genapp.map.resolutions = [<?php echo  $this->resolutions ?>];
	Genapp.map.numZoomLevels = [<?php echo  $this->numZoomLevels ?>];
	Genapp.map.projection = '<?php echo  $this->projection ?>';
	Genapp.map.tilesize= <?php echo  $this->tilesize ?>;

	Genapp.map.x_min= <?php echo  $this->bbox_x_min ?>;
	Genapp.map.y_min= <?php echo  $this->bbox_y_min ?>;
	Genapp.map.x_max= <?php echo  $this->bbox_x_max ?>;
	Genapp.map.y_max= <?php echo  $this->bbox_y_max ?>;
	
	Genapp.map.featureinfo_margin = <?php echo  $this->featureinfo_margin ?>;
	Genapp.map.featureinfo_typename = '<?php echo  $this->featureinfo_typename ?>';
	Genapp.map.featureinfo_maxfeatures = <?php echo  $this->featureinfo_maxfeatures ?>;

