<H1><?= $this->translate('File metadata');?></H1>

<div class="password-change-user-name">
    <?=$this->translate('Meta data of the file:');?>&nbsp;<b><?=$this->file?></b>
</div>

<table class="sectiontable">
<tr>
	<th><?=$this->translate('Meta Name');?></th>
	<th><?=$this->translate('Meta Value');?></th>
</tr>

<?php
$i = 0;
  foreach ($this->metaValues as $metaName => $metaValue) {
?>
<tr class="sectiontableentry<?=$i % 2?>">
	<td><?=$metaName?></td>
	<td><?=$metaValue?></td>
</tr>
<?php
$i++;
}
?>
</table>
 
<p class="subTableLink">
    <a href="<?= ""/*$this->url(array('controller'=>'pdfmetadata', 'action'=>'editmeta', 'file' =>urlencode($this->file) ),'default', true) */?>" title="<?=$this->translate('Edit the Metadata')?>" onClick="alert('<?=$this->translate("Not implemented");?>')"><?= $this->translate("Edit the Metadata")?></a>
    &nbsp;/&nbsp;&nbsp;<a href="<?= $this->url(array('controller'=>'fileindexation', action=>'parsepdf', 'file' =>urlencode($this->file), 'INDEX_KEY'=>$this->indexKey), 'default', true) ?>"><?= $this->translate('View the file content');?></a>
    &nbsp;/&nbsp;&nbsp;<a href="<?= $this->url(array('controller'=>'pdfmetadata', action=>'list', 'INDEX_KEY'=>$this->indexKey), 'default', true) ?>"><?= $this->translate('Back');?></a>
</p>