<?php
/**
 * Welcome view for french users.
 * @package views
 */
?>
<h1>Bienvenue sur le site internet E-forest !</h1>

<div class="content">
<br/>

<h2>Qu’est-ce qu’E-forest ?</h2> 
E-forest est une plate-forme développée dans le cadre d’un projet avec la Commission Européenne. <br/>
Un contrat cadre a été établi pour élargir et développer les connaissances de base du Centre de Données sur les Forêts Européennes (<a href="http://efdac.jrc.ec.europa.eu/">EFDAC</a>) géré par le Centre Commun de Recherche (CCR) de la Commission Européenne.<br/>
<br/>

Le contrat cadre appelé "Framework contract for the provision of forest data and services in support to the EFDAC" est entré en vigueur le 15 Octobre 2008 pour une durée de 48 mois.

<h2>Objectifs</h2> 
Les principaux objectifs de la plate-forme sont :
<ul>
<li>Fournir une perspective sur l’information forestière à un niveau européen afin de répondre aux problématiques importantes pour les politiques européennes relatives aux forêts;</li>
<li>Fournir aux décisionnaires de l’Union Européenne des données et informations forestières traitées, vérifiées, de qualité et actualisée au sein de l’Union Européenne et sur les territoires ou les politiques européennes sont appliquées.</li>
</ul>
<br/>

<h2>Fonctionnement</h2> 
A partir d’un besoin spécifique du CCR, le consortium E-forest élabore une proposition technique pour des services d’analyse thématique ou de traitement de données. Si la proposition est acceptée par le CCR, un Contract Spécifique (CS) est signé entre le CCR et le consortium E-forest. Le premier CS signé a été l’établissement des bases de la plate-forme E-forest. D’autres CS sont en cours, ils concernent l’enrichissement de la plate-forme E-forest avec des données relatives aux forêts ou de nouveaux modules pour la plate-forme.<br/>

<h2>Membres</h2> 
A ce jour 13 pays européens font partie du consortium E-forest.<br/>
Le nombre de membres du consortium n’est pas fixé. Chaque pays ou organisme collectant des données forestières nationales peut rejoindre le consortium à tout moment.<br/>
<br/>
<img height="400" src="<?=PATH_BASE_URL.'/img/Members.jpg'?>">
</div>
