<?php
/**
 * Welcome view for english users.
 * @package views
 */
?>
<h1>Welcome to the E-forest web site!</h1>

<div class="content">
<br/>

<h2>What is E-forest?</h2> 
E-forest is a platform developed in the context of a project with the European Commission. <br/>
A framework Contract has been established to broaden and develop the knowledge base of the European Forest Data Centre (<a href="http://efdac.jrc.ec.europa.eu/">EFDAC</a>) hosted by the Joint Research Centre (JRC) of the European commission.<br/>
<br/>

The framework contract called "Framework contract for the provision of forest data and services in support to the EFDAC has entered into force on October 15, 2008, for a duration of 48 months.

<h2>Objectives</h2> 
The main objectives of the platform are:
<ul>
<li>to provide a perspective on forest information at a European level by producing work and advice on issues that are potentially relevant to EU forest related policies;</li>
<li>to supply European Union decision-makers with processed, quality checked and timely policy relevant forest data and information within the EU and territories where EU policies are operating.</li>
</ul>
<br/>

<h2>Mechanism</h2> 
From a specific need of the JRC, the E-forest consortium is requested to elaborate a technical proposal for thematic analysis services or data processing services. <br/>
If the proposal is accepted by the JRC, it leads to a Specific Contract (SC) between the JRC and the E-forest consortium. <br/>
The basement of the E-forest platform is the first SC. <br/>
Other SC are in progress, which concern the enrichment of the E-forest platform with forest related data or new platform modules.<br/>
<br/>

<h2>Members</h2> 
To date 13 European countries are part of the E-forest consortium. <br/>
The number of consortium members is not fixed. Any country or organization which collects national forest data can join the consortium at any time.<br/>
<br/>
<img height="400" src="<?=PATH_BASE_URL.'/img/Members.jpg'?>" />
</div>